'use node';
import {internalAction} from './_generated/server';
import {internal} from './_generated/api';
import {v} from 'convex/values';
import {ConvexHttpClient} from 'convex/browser';
import {makeFunctionReference} from 'convex/server';
import type {Doc} from './_generated/dataModel';
import {load} from 'cheerio';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
export const primeNews=internalAction({args:{},handler:async(ctx):Promise<{scheduled:number}>=>{const people:Doc<'politicians'>[]=await ctx.runQuery(internal.activity.people,{});for(let i=0;i<people.length;i++)await ctx.scheduler.runAfter(i*1000,internal.activityActions.news,{externalId:people[i].externalId});return {scheduled:people.length};}});
// No paid API calls or AI enrichment. Rotate six precise name searches per hour.
export const news=internalAction({args:{externalId:v.optional(v.string())},handler:async(ctx,args):Promise<{inserted:number;checked:number;errors:string[]}>=>{
 const people:Doc<'politicians'>[]=await ctx.runQuery(internal.activity.people,{});const offset=(Math.floor(Date.now()/3600000)*6)%Math.max(people.length,1);const selected=args.externalId?people.filter(p=>p.externalId===args.externalId):Array.from({length:Math.min(6,people.length)},(_,i)=>people[(offset+i)%people.length]);const errors:string[]=[];let inserted=0;
 for(const p of selected)try{
  const name=p.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'');const aliases=p.externalId==='GOV-006'?[name,'Aixa Santamaria']:[name];const query=aliases.map(alias=>'"'+alias+'"').join(' OR ');const url=`https://news.google.com/rss/search?q=${encodeURIComponent('('+query+') Panamá when:90d')}&hl=es-419&gl=PA&ceid=PA:es-419`;
  const response=await fetch(url,{signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`HTTP ${response.status}`);const xml=load(await response.text(),{xmlMode:true});const items=xml('item').toArray().slice(0,15).flatMap(node=>{const item=xml(node);const publishedAt=Date.parse(item.find('pubDate').text());const title=item.find('title').text();const text=normalize(title+' '+item.find('description').text());if(!Number.isFinite(publishedAt)||!aliases.some(alias=>text.includes(normalize(alias))))return [];return [{politicianId:p._id,kind:'news' as const,sourceUrl:item.find('link').text().trim(),sourceName:item.find('source').text()||'Google News',title,summary:load(item.find('description').text()).text().trim().slice(0,350),publishedAt}];});inserted+=await ctx.runMutation(internal.activity.ingest,{items});
 }catch(e){errors.push(`${p.externalId}: ${String(e)}`);}await ctx.runMutation(internal.activity.logRun,{kind:'news',inserted,errors});return {inserted,checked:selected.length,errors};
}});
// Reuse Monitor's collected posts, never rescrape or backfill its accounts here.
export const socialArchive=internalAction({args:{},handler:async(ctx):Promise<{inserted:number;matched:number}>=>{
 const people:Doc<'politicians'>[]=await ctx.runQuery(internal.activity.people,{});const monitor=new ConvexHttpClient('https://graceful-perch-508.convex.cloud');const posts=await monitor.query(makeFunctionReference<'query',{limit:number;category:string},Array<{entityName:string;platform:string;postUrl:string;caption?:string;postedAt:number;thumbnailStorageId?:string;thumbnailUrl?:string}>>('queries:getFeed'),{limit:500,category:'Politics'}) as Array<{entityName:string;platform:string;postUrl:string;caption?:string;postedAt:number;thumbnailStorageId?:string;thumbnailUrl?:string}>;
 const items=posts.flatMap(post=>{const author=people.filter(p=>normalize(p.name)===normalize(post.entityName));const matches=author;return matches.length===1?[{politicianId:matches[0]._id,kind:'social' as const,sourceUrl:post.postUrl,sourceName:post.entityName,title:post.caption?Array.from(post.caption).slice(0,180).join(''):'Publicación',summary:post.caption?Array.from(post.caption).slice(0,700).join(''):undefined,platform:post.platform==='twitter'?'x_twitter':post.platform,publishedAt:post.postedAt,...(post.thumbnailUrl?.startsWith('https://')?{imageUrl:post.thumbnailUrl}:{})}]:[];});let inserted=0;for(let i=0;i<items.length;i+=50)inserted+=await ctx.runMutation(internal.activity.ingest,{items:items.slice(i,i+50)});await ctx.runMutation(internal.activity.logRun,{kind:'social-archive',inserted,errors:[]});return {inserted,matched:items.length};
}});
/** Verified recent coverage missed by exact-title RSS matching; source pages contain Didiano Pinilla in their article text. */
export const seedVerifiedDidianoNews=internalAction({args:{},handler:async(ctx):Promise<{inserted:number}>=>{const people:Doc<'politicians'>[]=await ctx.runQuery(internal.activity.people,{});const person=people.find(p=>p.externalId==='DEP-056');if(!person)throw Error('DEP-056 no encontrado');const items=[
 {politicianId:person._id,kind:'news' as const,sourceUrl:'https://www.asamblea.gob.pa/Noticias/Cultura%20Y%20Deporte/ESTUDIANTES-DE-PANAMA-Y-DEL-INTERIOR-VISITAN-LA-ASAMBLEA-NACIONAL',sourceName:'Asamblea Nacional de Panamá',sourceLogoUrl:'/icons/official/asamblea-nacional.png',title:'Estudiantes de Panamá y del interior visitan la Asamblea Nacional',summary:'Didiano Pinilla gestionó la visita de estudiantes del Centro Educativo Básico General Cascajilloso, de Mariato, al Palacio Justo Arosemena.',publishedAt:Date.parse('2026-08-12T13:57:00-05:00'),imageUrl:'https://www.asamblea.gob.pa/Uploads/noticias/banners/3061/banner_2026_08_12_14_34_14_874.jpg',mediaKind:'image' as const},
 {politicianId:person._id,kind:'news' as const,sourceUrl:'https://www.prensa.com/politica/ejecutivo-discute-con-diputados-sobre-reformas-en-el-sector-de-energia-sin-vamos-y-seguimos/',sourceName:'La Prensa Panamá',sourceLogoUrl:'/icons/media/laprensa.svg',title:'Ejecutivo negocia reformas eléctricas con diputados, pero deja fuera a Vamos y Seguimos',summary:'Didiano Pinilla participó en la reunión con el Ejecutivo sobre una propuesta para modificar la regulación del sector eléctrico.',publishedAt:Date.parse('2026-08-11T18:05:06.970Z'),imageUrl:'https://www.prensa.com/resizer/v2/YUW4HOYFGNA5ZB2LJZHRFF3SJY.jpeg?auth=3d1a8e93b912157430fb74005c35393ed9cfb13c14382feca6c276b9ae6743fd&width=1200',mediaKind:'image' as const},
 {politicianId:person._id,kind:'news' as const,sourceUrl:'https://www.asamblea.gob.pa/Noticias/Grupos%20De%20Amistad/SE-INSTALA-GRUPO-INTERPARLAMENTARIO-PANAMA-UCRANIA',sourceName:'Asamblea Nacional de Panamá',sourceLogoUrl:'/icons/official/asamblea-nacional.png',title:'Se instala Grupo Interparlamentario Panamá-Ucrania',summary:'Didiano Pinilla fue juramentado como presidente del Grupo de Amistad Interparlamentario Panamá-Ucrania.',publishedAt:Date.parse('2026-03-24T16:15:00-05:00')}
 ];return{inserted:await ctx.runMutation(internal.activity.ingest,{items})};}});

/** Current official reporting for the Chiriqui governor, verified against the publishing agencies. */
export const seedVerifiedGovernorNews=internalAction({args:{},handler:async(ctx):Promise<{inserted:number}>=>{const people:Doc<'politicians'>[]=await ctx.runQuery(internal.activity.people,{});const person=people.find(p=>p.externalId==='GOV-006');if(!person)throw Error('GOV-006 no encontrado');const items=[
 {politicianId:person._id,kind:'news' as const,sourceUrl:'https://www.migracion.gob.pa/migracion-se-suma-a-segunda-caminata-familiar-inclusiva-en-chiriqui/',sourceName:'Servicio Nacional de Migración',title:'Migración participa de segunda caminata familiar inclusiva en Chiriquí',summary:'La gobernadora Aixa Santamaría lideró la caminata familiar inclusiva interinstitucional organizada por la Gobernación de Chiriquí en el Parque de Las Madres, en David.',publishedAt:Date.parse('2026-09-13T12:00:00-05:00'),imageUrl:'https://www.migracion.gob.pa/wp-content/uploads/chiriqui-caminata-1-.jpg',mediaKind:'image' as const},
 {politicianId:person._id,kind:'news' as const,sourceUrl:'https://www.mingob.gob.pa/seguimos-avanzando-con-los-recorridos-por-las-provincias-del-pais/',sourceName:'Ministerio de Gobierno',title:'Recorrido institucional aborda la justicia comunitaria en Chiriquí',summary:'El Ministerio de Gobierno se reunió con la gobernadora Aixa Santamaría para coordinar asuntos de justicia comunitaria en la provincia.',publishedAt:Date.parse('2026-08-11T12:00:00-05:00')},
 ];return{inserted:await ctx.runMutation(internal.activity.ingest,{items})};}});
