'use node';
import {internalAction} from './_generated/server';
import {internal} from './_generated/api';
import {v} from 'convex/values';
import {load} from 'cheerio';

const logos:[RegExp,string][]=[[/tvn/i,'tvn.svg'],[/prensa/i,'laprensa.svg'],[/telemetro/i,'telemetro.svg'],[/eco\s*tv/i,'ecotv.svg']];
function safeUrl(input:string){try{const u=new URL(input);return u.protocol==='https:'&&!/^(localhost|127\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|\[)/.test(u.hostname)&&u.hostname.includes('.')?u:null;}catch{return null;}}
async function get(url:string){if(!safeUrl(url))throw Error('URL no pública');const response=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{'User-Agent':'Mozilla/5.0 (compatible; ORWELL-Panama/1.0)'}});if(!response.ok)throw Error(`HTTP ${response.status}`);if(!safeUrl(response.url))throw Error('Redirección no pública');return response;}
function decodeNewsUrl(url:string){const id=url.match(/\/articles\/([^?]+)/)?.[1];if(!id)return null;try{const decoded=Buffer.from(id,'base64url').toString('latin1');return decoded.match(/https:\/\/[^\s\x00-\x20\x7f-\xff]+/)?.[0]||null;}catch{return null;}}
// Google News RPC parameters documented by the MIT-licensed google_news_decoder project:
// https://github.com/dbernheisel/google_news_decoder
async function resolveNews(url:string,html:string){const $=load(html);const direct=$('[data-n-au]').attr('data-n-au');if(direct&&safeUrl(direct)&&!direct.includes('google.com'))return direct;const id=url.match(/\/(?:articles|read)\/([^?]+)/)?.[1];let signature=$('[data-n-a-sg]').attr('data-n-a-sg'),timestamp=$('[data-n-a-ts]').attr('data-n-a-ts');if(id&&(!signature||!timestamp)){const page=await get(`https://news.google.com/articles/${id}`);const doc=load(await page.text());signature=doc('[data-n-a-sg]').attr('data-n-a-sg');timestamp=doc('[data-n-a-ts]').attr('data-n-a-ts');}if(!id||!signature||!timestamp||!Number.isFinite(Number(timestamp)))throw Error('Google News no expone parámetros del enlace original');const request=['garturlreq',[['X','X',['X','X'],null,null,1,1,'US:en',null,1,null,null,null,null,null,0,1],'X','X',1,[1,1,1],1,1,null,0,0,null,0],id,Number(timestamp),signature];const response=await fetch('https://news.google.com/_/DotsSplashUi/data/batchexecute',{method:'POST',signal:AbortSignal.timeout(12000),headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({'f.req':JSON.stringify([[['Fbv4je',JSON.stringify(request)]]])})});if(!response.ok)throw Error(`Google News RPC HTTP ${response.status}`);for(const line of (await response.text()).split('\n')){if(!line.startsWith('[['))continue;try{const chunks=JSON.parse(line);for(const chunk of chunks){if(chunk[1]!=='Fbv4je'||typeof chunk[2]!=='string')continue;const result=JSON.parse(chunk[2]);if(result[0]==='garturlres'&&safeUrl(result[1])&&!result[1].includes('google.com'))return result[1] as string;}}catch{}}throw Error('Google News no devolvió el enlace original');}
async function articleImage(sourceUrl:string){let url=sourceUrl;if(url.includes('news.google.com')){const decoded=decodeNewsUrl(url);if(decoded)url=decoded;}const response=await get(url);const html=await response.text();if(html.length>3000000)throw Error('Página demasiado grande');const $=load(html);if(response.url.includes('news.google.com'))return articleImage(await resolveNews(sourceUrl,html));const image=$('meta[property="og:image"]').attr('content')||$('meta[name="twitter:image"]').attr('content');if(!image)throw Error('El medio no publica imagen de artículo');return new URL(image,response.url).href;}
async function socialImage(sourceUrl:string,current?:string){const parsed=safeUrl(sourceUrl);if(!parsed)return current;if(/(^|\.)instagram\.com$/.test(parsed.hostname)&&/^\/(p|reel)\//.test(parsed.pathname))return `${parsed.origin}${parsed.pathname.replace(/\/$/,'')}/media/?size=l`;if(/(^|\.)tiktok\.com$/.test(parsed.hostname)){const response=await get(`https://www.tiktok.com/oembed?url=${encodeURIComponent(sourceUrl)}`);const data=await response.json() as {thumbnail_url?:string};return data.thumbnail_url||current;}return current;}

/** Free bounded enrichment. Caller repeats with returned cursor; no paid API or video downloads. */
export const backfill=internalAction({args:{cursor:v.optional(v.string()),limit:v.optional(v.number()),ids:v.optional(v.array(v.id('activity')))},handler:async(ctx,args):Promise<{cursor:string;done:boolean;scanned:number;stored:number;logos:number;errors:string[]}>=>{
 const page=args.ids?{page:await ctx.runQuery(internal.activityMedia.byIds,{ids:args.ids.slice(0,25)}),continueCursor:'',isDone:true}:await ctx.runQuery(internal.activityMedia.candidates,{paginationOpts:{cursor:args.cursor||null,numItems:Math.max(1,Math.min(args.limit||25,25))}});let stored=0,logoCount=0;const errors:string[]=[];
 for(let offset=0;offset<page.page.length;offset+=5)await Promise.all(page.page.slice(offset,offset+5).map(async row=>{const logo=logos.find(([match])=>match.test(row.sourceName))?.[1];if(logo&&!row.sourceLogoUrl){await ctx.runMutation(internal.activityMedia.update,{id:row._id,sourceLogoUrl:`/icons/media/${logo}`});logoCount++;}
  if(row.imageUrl?.includes('.convex.cloud/'))return;
  try{const image=row.kind==='news'?await articleImage(row.sourceUrl):await socialImage(row.sourceUrl,row.imageUrl);if(!image)return;if(row.mediaKind==='video'||/\.mp4(?:\?|$)/i.test(image))return;const response=await get(image);const type=response.headers.get('content-type')?.split(';')[0]||'';if(!['image/jpeg','image/png','image/webp','image/gif','image/avif'].includes(type))throw Error(`Tipo de imagen rechazado: ${type}`);if(Number(response.headers.get('content-length'))>8000000)throw Error('Imagen supera 8 MB');const bytes=await response.arrayBuffer();if(bytes.byteLength>8000000)throw Error('Imagen supera 8 MB');const storageId=await ctx.storage.store(new Blob([bytes],{type}));const permanent=await ctx.storage.getUrl(storageId);if(permanent){await ctx.runMutation(internal.activityMedia.update,{id:row._id,imageUrl:permanent,mediaKind:'image'});stored++;}}
  catch(error){errors.push(`${row._id}: ${error instanceof Error?error.message:String(error)}`);}
 }));
 await ctx.runMutation(internal.activity.logRun,{kind:'activity-media',inserted:stored,errors});return{cursor:page.continueCursor,done:page.isDone,scanned:page.page.length,stored,logos:logoCount,errors};
}});
/** Enrich the first four currently visible items for every profile, rather than import-order archives. */
export const prime=internalAction({args:{},handler:async(ctx):Promise<{items:number;batches:number}>=>{const ids=await ctx.runQuery(internal.activityMedia.visibleCandidates,{});let batches=0;for(let offset=0;offset<ids.length;offset+=25){await ctx.scheduler.runAfter(batches*30000,internal.activityMediaActions.backfill,{ids:ids.slice(offset,offset+25)});batches++;}return{items:ids.length,batches};}});
