import {internalQuery,internalMutation} from './_generated/server';
import {v} from 'convex/values';
export const reports=internalQuery({args:{},handler:async(ctx)=>{const rows=await ctx.db.query('legislativeReports').collect();return rows.map(r=>r.reportId);}});
export const complete=internalMutation({args:{reportIds:v.array(v.number())},handler:async(ctx,{reportIds})=>{for(const reportId of reportIds){const old=await ctx.db.query('legislativeReports').withIndex('by_report',q=>q.eq('reportId',reportId)).first();if(!old)await ctx.db.insert('legislativeReports',{reportId,completedAt:Date.now()});}}});
const voteValidator=v.object({voteId:v.number(),votingId:v.number(),questionId:v.number(),questionText:v.string(),questionPassed:v.boolean(),votesNeeded:v.number(),totalAFavor:v.number(),totalEnContra:v.number(),totalAbstencion:v.number(),deputyId:v.number(),deputyName:v.string(),partyCode:v.string(),circuit:v.string(),vote:v.string(),isSuplente:v.boolean(),sessionDate:v.number(),votingTitle:v.string()});
export const ingest=internalMutation({args:{reportId:v.number(),sessionId:v.number(),sessionDate:v.number(),votingId:v.number(),votingTitle:v.string(),records:v.array(voteValidator)},handler:async(ctx,args)=>{
 let inserted=0;for(const record of args.records){const old=await ctx.db.query('votingRecords').withIndex('by_voteId',q=>q.eq('voteId',record.voteId)).first();if(old)continue;const profile=await ctx.db.query('deputyVotingProfiles').withIndex('by_deputyId',q=>q.eq('deputyId',record.deputyId)).first();await ctx.db.insert('votingRecords',{...record,...(profile?.politicianId?{politicianId:profile.politicianId}:{}),createdAt:Date.now(),updatedAt:Date.now()});inserted++;}
 const existing=await ctx.db.query('votingSessions').withIndex('by_votingId',q=>q.eq('votingId',args.votingId)).first();if(!existing)await ctx.db.insert('votingSessions',{reportId:args.reportId,sessionId:args.sessionId,sessionDate:args.sessionDate,votingId:args.votingId,votingTitle:args.votingTitle,sessionType:'Ordinaria',createdAt:Date.now(),updatedAt:Date.now()});return inserted;
}});
export const aggregate=internalMutation({args:{deputyId:v.number()},handler:async(ctx,{deputyId})=>{
 const profile=await ctx.db.query('deputyVotingProfiles').withIndex('by_deputyId',q=>q.eq('deputyId',deputyId)).first();if(!profile)return;
 const records=await ctx.db.query('votingRecords').withIndex('by_deputyId',q=>q.eq('deputyId',deputyId)).collect();
 const dates=[...new Set(records.map(r=>new Date(typeof r.sessionDate==='number'?r.sessionDate:r.sessionDate).toISOString().slice(0,10)))].sort();const months=new Map<string,{month:string;totalVotes:number;aFavor:number;enContra:number;abstencion:number}>();
 for(const r of records){const month=new Date(r.sessionDate).toISOString().slice(0,7);const m=months.get(month)||{month,totalVotes:0,aFavor:0,enContra:0,abstencion:0};m.totalVotes++;if(r.vote==='a_favor')m.aFavor++;else if(r.vote==='en_contra')m.enContra++;else if(r.vote==='abstencion')m.abstencion++;months.set(month,m);}
 await ctx.db.patch(profile._id,{totalVotes:records.length,totalAFavor:records.filter(r=>r.vote==='a_favor').length,totalEnContra:records.filter(r=>r.vote==='en_contra').length,totalAbstencion:records.filter(r=>r.vote==='abstencion').length,sessionsAttended:dates.length,firstVoteDate:Date.parse(dates[0]),lastVoteDate:Date.parse(dates.at(-1)!),updatedAt:Date.now()});
 const analytics=await ctx.db.query('deputyAnalytics').withIndex('by_deputyId',q=>q.eq('deputyId',deputyId)).first();if(analytics)await ctx.db.patch(analytics._id,{monthlyStats:[...months.values()].map(m=>({...m,pctAFavor:m.totalVotes?m.aFavor/m.totalVotes*100:0})).sort((a,b)=>a.month.localeCompare(b.month)),attendanceDates:dates});
}});
