'use client';
import Link from 'next/link';
import {ActivityFeed} from '@/components/reference/ActivityFeed';
import {useState,useMemo} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {ArrowRight,ArrowUpRight,Search,SlidersHorizontal,Scale,X,LayoutGrid,List} from 'lucide-react';
import {Portrait} from '@/components/reference/Portrait';
import {PARTY_LABELS,getPartyLogoPath,ROLE_CATEGORIES} from '@/lib/constants';
import type {Politician} from '@/lib/types';
type Tier={label:string;sublabel:string;total:number;slices:{code:string;count:number;color:string}[]};
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function HomeClient({politicians,parties,provinces,govTiers}:{politicians:Politician[];parties:string[];provinces:string[];govTiers:Tier[]}){
 const outer=useSearchParams();const params=outer.get('path')?new URLSearchParams(outer.get('path')!.split('?')[1]||''):outer;const router=useRouter();const [search,setSearch]=useState(params.get('search')||'');const [party,setParty]=useState(params.get('party')||'');const [role,setRole]=useState(params.get('role')||'');const [province,setProvince]=useState(params.get('province')||'');const [sort,setSort]=useState('name');const [view,setView]=useState('grid');const [selected,setSelected]=useState<string[]>([]);
 const filtered=useMemo(()=>politicians.filter(p=>(!search||normalize(`${p.name} ${p.partyFull} ${p.province}`).includes(normalize(search)))&&(!party||p.party===party)&&(!province||p.province===province)&&(!role||p.roleCategory===role||(role==='Party Leader'&&p.isPartyLeader))).sort((a,b)=>sort==='party'?a.party.localeCompare(b.party)||a.name.localeCompare(b.name):sort==='province'?a.province.localeCompare(b.province)||a.name.localeCompare(b.name):a.name.localeCompare(b.name)),[politicians,search,party,province,role,sort]);
 const updateUrl=(updates:Record<string,string>)=>{const next=new URLSearchParams({search,party,role,province,...updates});for(const [k,v] of [...next])if(!v)next.delete(k);const path=`/?${next}`;window.history.replaceState(null,'',window.location.pathname==='/multiplayer'?`/multiplayer?path=${encodeURIComponent(path)}`:path);};
 const reset=()=>{setSearch('');setParty('');setRole('');setProvince('');window.history.replaceState(null,'',window.location.pathname==='/multiplayer'?'/multiplayer?path=%2F':'/');};
 return <div className="reference-world"><div className="directory-intro"><div className="reference-wrap intro-grid"><div><h1>La política tiene nombres.<br/><span>Conoce su trayectoria.</span></h1><p>Perfiles públicos de Panamá. Consulta sus documentos y sigue el rastro de sus decisiones.</p><label className="directory-search"><Search size={22}/><input aria-label="Buscar políticos" placeholder="Busca un nombre, partido o provincia" value={search} onChange={e=>{setSearch(e.target.value);updateUrl({search:e.target.value});}}/>{search&&<button onClick={()=>{setSearch('');updateUrl({search:''});}} aria-label="Borrar búsqueda"><X size={17}/></button>}<span>Panamá</span></label><div className="search-hints">Explora <Link href="/?role=Deputy" onClick={()=>setRole('Deputy')}>Asamblea Nacional</Link><span>·</span><Link href="/?role=Mayor" onClick={()=>setRole('Mayor')}>Alcaldías</Link></div></div><aside className="directory-context"><div className="context-heading"><strong>Panamá</strong><span>Perfiles en el directorio</span></div>{govTiers.filter(t=>t.total>0).map(t=><Link className="institution-row" key={t.label} onClick={()=>setRole(t.label==='Asamblea Nacional'?'Deputy':t.label==='Presidente'?'President':t.label==='Alcaldes'?'Mayor':t.label==='Gobernadores'?'Governor':'Party Leader')} href={`/?role=${encodeURIComponent(t.label==='Asamblea Nacional'?'Deputy':t.label==='Presidente'?'President':t.label==='Alcaldes'?'Mayor':t.label==='Gobernadores'?'Governor':'Party Leader')}`}><span>{t.label}</span><div className="composition-bar">{t.slices.map(s=><i key={s.code} style={{backgroundColor:s.color,flex:s.count}} title={`${s.code}: ${s.count}`}/>)}</div><strong>{t.total}</strong></Link>)}<p>Cobertura del directorio, no censo de cargos. Una persona puede ejercer más de un rol.</p></aside></div></div>
 <div className="reference-wrap"><ActivityFeed compact/><nav className="explore-switch"><Link href="/territorios">Explorar territorios</Link><Link href="/comisiones">Comisiones</Link><Link href="/partidos">Partidos</Link></nav><div className="directory-toolbar"><div className="filter-fields"><SlidersHorizontal size={17}/><select aria-label="Filtrar por cargo" value={role} onChange={e=>{setRole(e.target.value);updateUrl({role:e.target.value});}}><option value="">Todos los cargos</option>{ROLE_CATEGORIES.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select><select aria-label="Filtrar por partido" value={party} onChange={e=>{setParty(e.target.value);updateUrl({party:e.target.value});}}><option value="">Todos los partidos</option>{parties.map(p=><option key={p} value={p}>{PARTY_LABELS[p]||p}</option>)}</select><select aria-label="Filtrar por provincia" value={province} onChange={e=>{setProvince(e.target.value);updateUrl({province:e.target.value});}}><option value="">Todas las provincias</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></div>{(search||party||province||role)&&<button className="clear-filter" onClick={reset}>Limpiar <X size={13}/></button>}</div>
 <div className="results-heading"><div><h2>Directorio de perfiles</h2><span role="status">{filtered.length} de {politicians.length} perfiles</span></div><div className="results-controls"><select aria-label="Ordenar perfiles" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Nombre A–Z</option><option value="party">Partido</option><option value="province">Provincia</option></select><button aria-label="Vista de tarjetas" aria-pressed={view==='grid'} onClick={()=>setView('grid')}><LayoutGrid size={18}/></button><button aria-label="Vista de lista" aria-pressed={view==='list'} onClick={()=>setView('list')}><List size={18}/></button></div></div>
 {filtered.length?<div className={view==='grid'?'directory-grid':'directory-list'}>{filtered.map(p=><article className="directory-card" key={p.id}><Link className="directory-person" href={`/politician/${p.id}`}><Portrait src={p.headshot} name={p.name} className="directory-portrait"/><div><span className="directory-role">{p.role}</span><h3>{p.name}</h3><p>{p.province}{p.circuit?` · ${p.circuit}`:''}</p></div><ArrowUpRight className="person-arrow" size={18}/></Link><div className="directory-card-bottom"><Link href={`/partidos/${p.party.toLowerCase()}`}><img src={getPartyLogoPath(p.party)} alt=""/>{p.party}</Link><span>{p.accounts.length} redes</span><button aria-label={`Comparar ${p.name}`} aria-pressed={selected.includes(p.id)} disabled={selected.length===2&&!selected.includes(p.id)} onClick={()=>setSelected(s=>s.includes(p.id)?s.filter(id=>id!==p.id):[...s,p.id])}><Scale size={14}/>{selected.includes(p.id)?'Añadido':'Comparar'}</button></div></article>)}</div>:<div className="no-results"><h3>No encontramos ese perfil</h3><p>Prueba otro nombre o elimina los filtros.</p><button className="record-button" onClick={reset}>Ver todos los perfiles</button></div>}
 <div className="directory-end"><p>Un registro útil también muestra lo que falta.</p><Link href="/metodologia">Fuentes y metodología <ArrowRight size={16}/></Link></div>
 </div>{selected.length>0&&<div className="comparison-tray"><Scale size={20}/><span>{selected.map(id=>politicians.find(p=>p.id===id)?.name).join(' / ')}</span><button disabled={selected.length<2} onClick={()=>router.push(window.location.pathname==='/multiplayer'?`/multiplayer?path=${encodeURIComponent(`/comparar?a=${selected[0]}&b=${selected[1]}`)}`:`/comparar?a=${selected[0]}&b=${selected[1]}`)}>Comparar {selected.length}/2 <ArrowRight size={16}/></button><button aria-label="Cancelar comparación" onClick={()=>setSelected([])}><X size={18}/></button></div>}</div>;
}
