'use client';

import {useEffect,useSyncExternalStore} from 'react';

export type SiteLanguage='es'|'en'|'pt';
const storageKey='orwell-panama-language';
const subscribeLanguage=(callback:()=>void)=>{window.addEventListener('storage',callback);return()=>window.removeEventListener('storage',callback)};
const readLanguage=():SiteLanguage=>{const saved=localStorage.getItem(storageKey);return saved==='en'||saved==='pt'?saved:'es'};
const readServerLanguage=():SiteLanguage=>'es';

const copy:Record<'en'|'pt',Record<string,string>>={
 en:{
  'Panamá':'Panama','Personas':'People','Cargos':'Offices','Partidos':'Parties','Fuentes':'Sources','Perfil':'Profile','Perfiles':'Profiles','Trayectoria':'Career','Votaciones':'Votes','Propuestas':'Proposals','Finanzas':'Finances','Redes':'Social','Comparar':'Compare','Políticos':'Politicians','Destacados':'Featured','Noticias':'News','Oficinas de Gobierno':'Public offices','Política':'Politics','Navegación principal':'Main navigation',
  'Buscar un nombre':'Search by name','Buscar políticos':'Search politicians','Busca un nombre, partido o provincia':'Search a name, party, or province','Borrar búsqueda':'Clear search','Menú de navegación':'Navigation menu','Menú de usuario':'User menu','Modo claro':'Light mode','Modo oscuro':'Dark mode','Perfil / Admin':'Profile / Admin','Cerrar sesión':'Sign out',
  'Cargo':'Office','Provincia':'Province','Circuito':'District','Ámbito':'Jurisdiction','Partido / agrupación':'Party / affiliation','Ficha institucional':'Official profile','Fuente oficial':'Official source','Volver al directorio':'Back to directory','Volver a Panamá':'Back to Panama','Todos los partidos':'All parties','Ver todos':'View all','Sitio oficial':'Official site','Institución de origen':'Source institution','Leer metodología':'Read methodology','Consultar metodología':'View methodology','Fuentes y metodología':'Sources and methodology',
  'Perfil profesional':'Professional profile','La ficha':'Profile record','Trayectoria y elecciones':'Career and elections','Documentos públicos':'Public documents','Comisiones registradas':'Recorded committees','El contexto importa':'Context matters','Documentos':'Documents','Nacimiento':'Birth date','Ciudadanía':'Citizenship','Salario personal':'Personal salary','Patrimonio declarado':'Declared assets','Archivo legislativo':'Legislative archive','Votos registrados':'Recorded votes','votos registrados':'recorded votes','Fechas con participación':'Dates with participation','fechas con votos':'voting dates','Última fecha del archivo':'Latest archive date','Últimos registros':'Latest records','Votos por año':'Votes by year','A favor':'In favor','En contra':'Against','Abstención':'Abstention',
  'Cargo registrado':'Recorded office','Fecha de nacimiento':'Date of birth','Lugar de nacimiento':'Place of birth','Suplente registrado':'Recorded alternate','No documentado':'Not documented','No documentada':'Not documented','Sin documentar':'Not documented','No consta':'Not available','No calculado':'Not calculated','Sin documentos enlazados.':'No linked documents.','Sin cuentas registradas.':'No recorded accounts.','Biografía pendiente de documentar.':'Biography pending documentation.','La biografía aún no está documentada en este perfil.':'The biography has not yet been documented in this profile.','Sin archivo legislativo vinculado.':'No linked legislative archive.','No hay documentos adjuntos.':'No attached documents.','Sin comisiones documentadas.':'No documented committees.',
  'Cuenta identificada':'Account identified','Identidad probable':'Likely identity','Publicaciones sin conectar':'Posts not connected','Actividad reciente':'Recent activity','Redes sociales':'Social media','Publicaciones y frecuencia':'Posts and frequency','Última publicación: sin datos':'Latest post: no data','Identificada en directorio':'Identified in directory','cuentas registradas':'recorded accounts',
  'Remuneración y patrimonio':'Compensation and assets','Planilla de despacho registrada':'Recorded office payroll','Patrimonio neto declarado':'Declared net worth','Patrimonio neto estimado':'Estimated net worth','Evidencia disponible':'Available evidence','Propuestas y formación':'Proposals and education','Fuentes y cobertura':'Sources and coverage','Archivo de la Asamblea Nacional':'National Assembly archive','Perfil y documentos':'Profile and documents','Metodología':'Methodology',
  'Propuesta Política':'Policy proposal','Plan de Gobierno':'Government plan','Ver PDF ↗':'View PDF ↗','Temas Prioritarios':'Priority issues','Áreas Estratégicas':'Strategic areas','Promesas Clave':'Key promises','Tiene indicadores':'Includes indicators','Perfil Profesional':'Professional profile','Educación':'Education','Experiencia Laboral':'Work experience','Cargos Políticos':'Political offices','Título no especificado':'Degree not specified','Cargo no especificado':'Office not specified','Declaración de Intereses':'Declaration of interests','Intereses Declarados':'Declared interests','Empresas':'Companies','Membresías':'Memberships','Fuentes Ingreso':'Income sources','Actividades Comerciales':'Business activities','Fuentes de Ingreso':'Sources of income','Parientes en Gobierno':'Relatives in government','Conflictos Declarados':'Declared conflicts','Declaración Patrimonial':'Asset declaration','Patrimonio Declarado':'Declared assets','Patrimonio Neto':'Net worth','Inmuebles':'Properties','Vehículos':'Vehicles','Cuentas':'Accounts','Deudas':'Debts','Bienes Inmuebles':'Real estate','Cuentas Bancarias':'Bank accounts','Inversiones':'Investments','Desglose de Votación':'Vote breakdown','Tendencia de Votación':'Voting trend','Sin datos de tendencia disponibles':'No voting-trend data available','Buscar proyecto o pregunta':'Search project or question','Ver pregunta':'View question',
  'Registro legislativo':'Legislative record','Registro de suplencia.':'Alternate-member record.','Vínculo y período pendientes de validación.':'Link and term pending validation.','Directorio':'Directory','Cobertura del directorio':'Directory coverage','Espacio Cívico · documentos públicos':'Espacio Cívico · public documents','Directorio de personas públicas':'Public officials directory','Asamblea Nacional':'National Assembly',
  'Resultados electorales y cambios de partido: sin una serie verificada en esta ficha.':'Election results and party changes: no verified series is available in this profile.','Este vínculo importado no acredita el mandato actual. Las sesiones con voto registrado no equivalen a una tasa de asistencia.':'This imported link does not establish the current term. Sessions with a recorded vote are not an attendance rate.','Importación histórica. Abre una votación para consultar su pregunta; no se infiere el resultado de una ley a partir de un voto individual.':'Historical import. Open a vote to view its question; the outcome of a law cannot be inferred from one individual vote.','Notas sobre participación, afinidad y rankings':'Notes on participation, alignment, and rankings',
  'Accede a las cuentas identificadas en el directorio. La actividad reciente aún no está conectada a esta ficha.':'Open the accounts identified in the directory. Recent activity is not yet connected to this profile.','No hay publicaciones importadas en esta aplicación. Cada publicación mostrará su plataforma, fecha y enlace de origen cuando se conecte el feed.':'No posts have been imported into this application. Each post will show its platform, date, and source link once the feed is connected.','No hay publicaciones importadas en esta aplicación. La red más activa y las últimas 5–10 publicaciones aparecerán cuando exista una fuente conectada y fechada. La prioridad de rastreo de una cuenta no mide su actividad.':'No posts have been imported into this application. The most active network and latest 5–10 posts will appear once a dated source is connected. An account’s tracking priority does not measure activity.',
  'Cada bloque distingue el registro del directorio, el archivo legislativo y los documentos de terceros. No se presenta una calificación global de la persona.':'Each section distinguishes directory records, legislative archives, and third-party documents. The site does not assign an overall rating to a person.','Identificación de cuentas, sin sincronización de publicaciones ni fecha de última actividad.':'Account identification, without post synchronization or a latest-activity date.','Extracción automática de documentos importados. Las propuestas son compromisos publicados, no resultados verificados.':'Automated extraction from imported documents. Proposals are published commitments, not verified outcomes.','No hay propuestas documentadas en esta ficha.':'No proposals are documented in this profile.',
  'La política tiene nombres.':'Politics has names.','Conoce su trayectoria.':'Know their record.','Perfiles públicos de Panamá. Consulta sus documentos y sigue el rastro de sus decisiones.':'Public profiles from Panama. Review their documents and follow the record of their decisions.','Explora':'Explore','Alcaldías':'Mayors','Perfiles en el directorio':'Profiles in the directory','Todos los cargos':'All offices','Todas las provincias':'All provinces','Limpiar':'Clear','Directorio de perfiles':'Profile directory','Nombre A–Z':'Name A–Z','Rango':'Rank','Añadido':'Added','No encontramos ese perfil':'We could not find that profile','Prueba otro nombre o elimina los filtros.':'Try another name or clear the filters.','Ver todos los perfiles':'View all profiles','Un registro útil también muestra lo que falta.':'A useful record also shows what is missing.','Cancelar comparación':'Cancel comparison',
  'Cargos públicos de Panamá':'Public offices in Panama','Explora los perfiles disponibles por función. Las cifras muestran la cobertura del directorio.':'Explore available profiles by role. Counts show the directory’s coverage.','Perfiles, lado a lado.':'Profiles, side by side.','Contrasta cargos y evidencia disponible. El volumen del archivo no mide el desempeño.':'Compare offices and available evidence. Archive volume does not measure performance.','Primer perfil':'First profile','Segundo perfil':'Second profile','Selecciona una persona':'Select a person','Ver perfil y fuentes':'View profile and sources','Selecciona dos perfiles distintos para abrir la comparación.':'Select two different profiles to open the comparison.',
  'El dato y su contexto.':'The data and its context.','Qué significa cada fecha':'What each date means','Redes y verificación':'Social accounts and verification','Documentos de terceros':'Third-party documents','Vacíos y correcciones':'Gaps and corrections','Pregunta sometida a votación':'Question put to a vote','Resultado de esta pregunta':'Result of this question','Aprobada':'Approved','Rechazada':'Rejected',
  'Datos de la':'Data from the','Este directorio es un proyecto de monitoreo cívico independiente. Las cuentas de redes sociales han sido verificadas mediante búsquedas públicas y fuentes oficiales.':'This directory is an independent civic-monitoring project. Social accounts have been verified through public searches and official sources.',
  'Diputado':'Member of Parliament','Diputada':'Member of Parliament','Diputados':'Members of Parliament','Presidente':'President','Presidente de la República':'President of the Republic','Alcalde':'Mayor','Alcaldesa':'Mayor','Alcaldes':'Mayors','Gobernador':'Governor','Gobernadora':'Governor','Gobernadores':'Governors','Representante':'Representative','Suplente':'Alternate member','Líderes de Partido':'Party leaders',
  'Hoja de vida':'Résumé','Propuesta política':'Policy proposal','Buscar':'Search','Idioma':'Language','Secciones del perfil':'Profile sections','POLÍTICA':'POLITICS','Nacional':'National','ARCHIVO':'ARCHIVE','LEGISLATIVO':'LEGISLATIVE',
  'Directorio ORWELL':'ORWELL Directory','registro actualizado':'record updated','actualizado':'updated','La fecha no certifica la vigencia del cargo.':'The date does not certify that the office is current.','La fecha del registro no certifica la vigencia del cargo.':'The record date does not certify that the office is current.','Consultar ficha institucional':'View official profile','Vínculo importado. Identidad y mandato pendientes de validación.':'Imported link. Identity and term pending validation.','Archivo enlazado desde Espacio Cívico. La presencia de un documento no implica auditoría.':'File linked from Espacio Cívico. A linked document does not imply an audit.','Importación sin período publicado.':'Imported without a published term.','Ver composición en la fuente':'View the source composition','Los votos del archivo pertenecen a su período de origen. No son una evaluación del cargo registrado hoy.':'Archived votes belong to their original term. They are not an assessment of the office held today.','Cómo leer los datos':'How to read the data','Asamblea Nacional de Panamá':'National Assembly of Panama','archivo importado.':'imported archive.','No mide asistencia al mandato actual.':'Does not measure attendance during the current term.','Segundo Debate al Proyecto de Ley No.':'Second Debate on Bill No.',
  'Votaciones del archivo':'Archived votes','No pudimos cargar el archivo. Vuelve a intentar recargando esta página.':'We could not load the archive. Reload the page to try again.','No hay un archivo de votaciones vinculado a este perfil. Para cargos ejecutivos, este indicador no aplica.':'No voting archive is linked to this profile. This indicator does not apply to executive offices.','Planilla: monto importado de Espacio Cívico, sin fecha de corte documentada. Corresponde al despacho, no al salario ni al patrimonio de la persona.':'Payroll amount imported from Espacio Cívico without a documented cutoff date. It belongs to the office, not to the person’s salary or assets.','Consultar monto en la fuente':'View the amount at the source','Resumen extraído automáticamente del documento. Comprueba el original antes de citarlo.':'Automatically extracted document summary. Check the original before citing it.','La falta de un documento aquí no demuestra que la persona no lo haya presentado.':'A missing document here does not show that the person failed to file it.',
  'Cargo y circunscripción. Registro del directorio:':'Office and constituency. Directory record:','Biografía, comisiones y declaraciones. La importación no conserva una fecha de corte pública; los valores pueden haber cambiado.':'Biography, committees, and declarations. The import has no public cutoff date, so the values may have changed.','Sin fechas disponibles.':'No dates available.','No hay enlace individual a acta en la importación.':'The import has no individual minutes link.','cuentas':'accounts','Más perfiles':'More profiles',
  'Cuenta con una licenciatura en Ingeniería en Sistemas de la Universidad Latina, Ingenería Eléctrica de la Universidad Tecnológica de Panamá y una maestría en Administración de Negocio de la Universidad Latina. En su trayectoria profesional, ha sido gerente de operaciones de Electra Noreste, gerente en Grupo Melo y gerente de operaciones de ETESA.':'He holds a bachelor’s degree in Systems Engineering from Universidad Latina, a degree in Electrical Engineering from Universidad Tecnológica de Panamá, and a master’s degree in Business Administration from Universidad Latina. His professional experience includes serving as operations manager at Electra Noreste, manager at Grupo Melo, and operations manager at ETESA.'
  ,'Archivo':'Archive','legislativo':'legislative','Relaciones Exteriores':'Foreign Affairs','Asuntos Municipales':'Municipal Affairs','Asuntos Agropecuarios':'Agricultural Affairs','Asuntos Indígenas':'Indigenous Affairs','Comercio y Asuntos Económicos':'Trade and Economic Affairs','Comunicación y Transporte':'Communications and Transportation','Credenciales, Reglamento, Ética Parlamentaria y Asuntos Judiciales':'Credentials, Rules, Parliamentary Ethics, and Judicial Affairs','Economía y Finanzas':'Economy and Finance','Educación, Cultura y Deportes':'Education, Culture, and Sports','Gobierno, Justicia y Asuntos Constitucionales':'Government, Justice, and Constitutional Affairs','Infraestructura Pública y Asuntos del Canal':'Public Infrastructure and Canal Affairs','Mujer, Niñez, Juventud y Familia':'Women, Children, Youth, and Family','Población, Ambiente y Desarrollo':'Population, Environment, and Development','Presupuesto':'Budget','Trabajo, Salud y Desarrollo Social':'Labor, Health, and Social Development'
 },
 pt:{
  'Panamá':'Panamá','Personas':'Pessoas','Cargos':'Cargos','Partidos':'Partidos','Fuentes':'Fontes','Perfil':'Perfil','Perfiles':'Perfis','Trayectoria':'Trajetória','Votaciones':'Votações','Propuestas':'Propostas','Finanzas':'Finanças','Redes':'Redes','Comparar':'Comparar','Políticos':'Políticos','Destacados':'Destaques','Noticias':'Notícias','Oficinas de Gobierno':'Cargos públicos','Política':'Política','Navegación principal':'Navegação principal',
  'Buscar un nombre':'Buscar por nome','Buscar políticos':'Buscar políticos','Busca un nombre, partido o provincia':'Busque um nome, partido ou província','Borrar búsqueda':'Limpar busca','Menú de navegación':'Menu de navegação','Menú de usuario':'Menu do usuário','Modo claro':'Modo claro','Modo oscuro':'Modo escuro','Perfil / Admin':'Perfil / Admin','Cerrar sesión':'Sair',
  'Cargo':'Cargo','Provincia':'Província','Circuito':'Distrito','Ámbito':'Âmbito','Partido / agrupación':'Partido / grupo','Ficha institucional':'Perfil institucional','Fuente oficial':'Fonte oficial','Volver al directorio':'Voltar ao diretório','Volver a Panamá':'Voltar ao Panamá','Todos los partidos':'Todos os partidos','Ver todos':'Ver todos','Sitio oficial':'Site oficial','Institución de origen':'Instituição de origem','Leer metodología':'Ler metodologia','Consultar metodología':'Consultar metodologia','Fuentes y metodología':'Fontes e metodologia',
  'Perfil profesional':'Perfil profissional','La ficha':'Ficha','Trayectoria y elecciones':'Trajetória e eleições','Documentos públicos':'Documentos públicos','Comisiones registradas':'Comissões registradas','El contexto importa':'O contexto importa','Documentos':'Documentos','Nacimiento':'Nascimento','Ciudadanía':'Cidadania','Salario personal':'Salário pessoal','Patrimonio declarado':'Patrimônio declarado','Archivo legislativo':'Arquivo legislativo','Votos registrados':'Votos registrados','votos registrados':'votos registrados','Fechas con participación':'Datas com participação','fechas con votos':'datas com votos','Última fecha del archivo':'Última data do arquivo','Últimos registros':'Registros recentes','Votos por año':'Votos por ano','A favor':'A favor','En contra':'Contra','Abstención':'Abstenção',
  'Cargo registrado':'Cargo registrado','Fecha de nacimiento':'Data de nascimento','Lugar de nacimiento':'Local de nascimento','Suplente registrado':'Suplente registrado','No documentado':'Não documentado','No documentada':'Não documentada','Sin documentar':'Não documentado','No consta':'Não informado','No calculado':'Não calculado','Sin documentos enlazados.':'Sem documentos vinculados.','Sin cuentas registradas.':'Sem contas registradas.','Biografía pendiente de documentar.':'Biografia pendente de documentação.','La biografía aún no está documentada en este perfil.':'A biografia ainda não foi documentada neste perfil.','Sin archivo legislativo vinculado.':'Sem arquivo legislativo vinculado.','No hay documentos adjuntos.':'Não há documentos anexados.','Sin comisiones documentadas.':'Sem comissões documentadas.',
  'Cuenta identificada':'Conta identificada','Identidad probable':'Identidade provável','Publicaciones sin conectar':'Publicações não conectadas','Actividad reciente':'Atividade recente','Redes sociales':'Redes sociais','Publicaciones y frecuencia':'Publicações e frequência','Última publicación: sin datos':'Última publicação: sem dados','Identificada en directorio':'Identificada no diretório','cuentas registradas':'contas registradas',
  'Remuneración y patrimonio':'Remuneração e patrimônio','Planilla de despacho registrada':'Folha do gabinete registrada','Patrimonio neto declarado':'Patrimônio líquido declarado','Patrimonio neto estimado':'Patrimônio líquido estimado','Evidencia disponible':'Evidência disponível','Propuestas y formación':'Propostas e formação','Fuentes y cobertura':'Fontes e cobertura','Archivo de la Asamblea Nacional':'Arquivo da Assembleia Nacional','Perfil y documentos':'Perfil e documentos','Metodología':'Metodologia',
  'Propuesta Política':'Proposta política','Plan de Gobierno':'Plano de governo','Ver PDF ↗':'Ver PDF ↗','Temas Prioritarios':'Temas prioritários','Áreas Estratégicas':'Áreas estratégicas','Promesas Clave':'Promessas principais','Tiene indicadores':'Inclui indicadores','Perfil Profesional':'Perfil profissional','Educación':'Educação','Experiencia Laboral':'Experiência profissional','Cargos Políticos':'Cargos políticos','Título no especificado':'Formação não especificada','Cargo no especificado':'Cargo não especificado','Declaración de Intereses':'Declaração de interesses','Intereses Declarados':'Interesses declarados','Empresas':'Empresas','Membresías':'Associações','Fuentes Ingreso':'Fontes de renda','Actividades Comerciales':'Atividades comerciais','Fuentes de Ingreso':'Fontes de renda','Parientes en Gobierno':'Parentes no governo','Conflictos Declarados':'Conflitos declarados','Declaración Patrimonial':'Declaração patrimonial','Patrimonio Declarado':'Patrimônio declarado','Patrimonio Neto':'Patrimônio líquido','Inmuebles':'Imóveis','Vehículos':'Veículos','Cuentas':'Contas','Deudas':'Dívidas','Bienes Inmuebles':'Bens imóveis','Cuentas Bancarias':'Contas bancárias','Inversiones':'Investimentos','Desglose de Votación':'Detalhamento da votação','Tendencia de Votación':'Tendência de votação','Sin datos de tendencia disponibles':'Sem dados disponíveis sobre tendência de votação','Buscar proyecto o pregunta':'Buscar projeto ou pergunta','Ver pregunta':'Ver pergunta',
  'Registro legislativo':'Registro legislativo','Registro de suplencia.':'Registro de suplência.','Vínculo y período pendientes de validación.':'Vínculo e período aguardando validação.','Directorio':'Diretório','Cobertura del directorio':'Cobertura do diretório','Espacio Cívico · documentos públicos':'Espacio Cívico · documentos públicos','Directorio de personas públicas':'Diretório de pessoas públicas','Asamblea Nacional':'Assembleia Nacional',
  'Resultados electorales y cambios de partido: sin una serie verificada en esta ficha.':'Resultados eleitorais e mudanças de partido: sem uma série verificada neste perfil.','Este vínculo importado no acredita el mandato actual. Las sesiones con voto registrado no equivalen a una tasa de asistencia.':'Este vínculo importado não comprova o mandato atual. Sessões com voto registrado não equivalem a uma taxa de presença.','Importación histórica. Abre una votación para consultar su pregunta; no se infiere el resultado de una ley a partir de un voto individual.':'Importação histórica. Abra uma votação para consultar a pergunta; o resultado de uma lei não pode ser inferido a partir de um voto individual.','Notas sobre participación, afinidad y rankings':'Notas sobre participação, alinhamento e classificações',
  'Accede a las cuentas identificadas en el directorio. La actividad reciente aún no está conectada a esta ficha.':'Acesse as contas identificadas no diretório. A atividade recente ainda não está conectada a este perfil.','No hay publicaciones importadas en esta aplicación. Cada publicación mostrará su plataforma, fecha y enlace de origen cuando se conecte el feed.':'Não há publicações importadas neste aplicativo. Cada publicação mostrará sua plataforma, data e link de origem quando o feed for conectado.','No hay publicaciones importadas en esta aplicación. La red más activa y las últimas 5–10 publicaciones aparecerán cuando exista una fuente conectada y fechada. La prioridad de rastreo de una cuenta no mide su actividad.':'Não há publicações importadas neste aplicativo. A rede mais ativa e as últimas 5–10 publicações aparecerão quando houver uma fonte conectada e datada. A prioridade de rastreamento de uma conta não mede sua atividade.',
  'Cada bloque distingue el registro del directorio, el archivo legislativo y los documentos de terceros. No se presenta una calificación global de la persona.':'Cada seção distingue o registro do diretório, o arquivo legislativo e documentos de terceiros. O site não atribui uma avaliação geral à pessoa.','Identificación de cuentas, sin sincronización de publicaciones ni fecha de última actividad.':'Identificação de contas, sem sincronização de publicações ou data da última atividade.','Extracción automática de documentos importados. Las propuestas son compromisos publicados, no resultados verificados.':'Extração automática de documentos importados. As propostas são compromissos publicados, não resultados verificados.','No hay propuestas documentadas en esta ficha.':'Não há propostas documentadas neste perfil.',
  'La política tiene nombres.':'A política tem nomes.','Conoce su trayectoria.':'Conheça suas trajetórias.','Perfiles públicos de Panamá. Consulta sus documentos y sigue el rastro de sus decisiones.':'Perfis públicos do Panamá. Consulte seus documentos e acompanhe o histórico de suas decisões.','Explora':'Explore','Alcaldías':'Prefeituras','Perfiles en el directorio':'Perfis no diretório','Todos los cargos':'Todos os cargos','Todas las provincias':'Todas as províncias','Limpiar':'Limpar','Directorio de perfiles':'Diretório de perfis','Nombre A–Z':'Nome A–Z','Rango':'Classificação','Añadido':'Adicionado','No encontramos ese perfil':'Não encontramos esse perfil','Prueba otro nombre o elimina los filtros.':'Tente outro nome ou remova os filtros.','Ver todos los perfiles':'Ver todos os perfis','Un registro útil también muestra lo que falta.':'Um registro útil também mostra o que está faltando.','Cancelar comparación':'Cancelar comparação',
  'Cargos públicos de Panamá':'Cargos públicos do Panamá','Explora los perfiles disponibles por función. Las cifras muestran la cobertura del directorio.':'Explore os perfis disponíveis por função. Os números mostram a cobertura do diretório.','Perfiles, lado a lado.':'Perfis lado a lado.','Contrasta cargos y evidencia disponible. El volumen del archivo no mide el desempeño.':'Compare cargos e evidências disponíveis. O volume do arquivo não mede o desempenho.','Primer perfil':'Primeiro perfil','Segundo perfil':'Segundo perfil','Selecciona una persona':'Selecione uma pessoa','Ver perfil y fuentes':'Ver perfil e fontes','Selecciona dos perfiles distintos para abrir la comparación.':'Selecione dois perfis diferentes para abrir a comparação.',
  'El dato y su contexto.':'Os dados e seu contexto.','Qué significa cada fecha':'O que cada data significa','Redes y verificación':'Redes e verificação','Documentos de terceros':'Documentos de terceiros','Vacíos y correcciones':'Lacunas e correções','Pregunta sometida a votación':'Questão submetida a votação','Resultado de esta pregunta':'Resultado desta questão','Aprobada':'Aprovada','Rechazada':'Rejeitada',
  'Datos de la':'Dados da','Este directorio es un proyecto de monitoreo cívico independiente. Las cuentas de redes sociales han sido verificadas mediante búsquedas públicas y fuentes oficiales.':'Este diretório é um projeto independente de monitoramento cívico. As contas de redes sociais foram verificadas por meio de buscas públicas e fontes oficiais.',
  'Diputado':'Deputado','Diputada':'Deputada','Diputados':'Deputados','Presidente':'Presidente','Presidente de la República':'Presidente da República','Alcalde':'Prefeito','Alcaldesa':'Prefeita','Alcaldes':'Prefeitos','Gobernador':'Governador','Gobernadora':'Governadora','Gobernadores':'Governadores','Representante':'Representante','Suplente':'Suplente','Líderes de Partido':'Líderes partidários',
  'Hoja de vida':'Currículo','Propuesta política':'Proposta política','Buscar':'Buscar','Idioma':'Idioma','Secciones del perfil':'Seções do perfil','POLÍTICA':'POLÍTICA','Nacional':'Nacional','ARCHIVO':'ARQUIVO','LEGISLATIVO':'LEGISLATIVO',
  'Directorio ORWELL':'Diretório ORWELL','registro actualizado':'registro atualizado','actualizado':'atualizado','La fecha no certifica la vigencia del cargo.':'A data não certifica que o cargo esteja vigente.','La fecha del registro no certifica la vigencia del cargo.':'A data do registro não certifica que o cargo esteja vigente.','Consultar ficha institucional':'Consultar perfil institucional','Vínculo importado. Identidad y mandato pendientes de validación.':'Vínculo importado. Identidade e mandato aguardam validação.','Archivo enlazado desde Espacio Cívico. La presencia de un documento no implica auditoría.':'Arquivo vinculado pelo Espacio Cívico. A presença de um documento não implica auditoria.','Importación sin período publicado.':'Importação sem período publicado.','Ver composición en la fuente':'Ver composição na fonte','Los votos del archivo pertenecen a su período de origen. No son una evaluación del cargo registrado hoy.':'Os votos do arquivo pertencem ao período de origem. Eles não avaliam o cargo registrado hoje.','Cómo leer los datos':'Como ler os dados','Asamblea Nacional de Panamá':'Assembleia Nacional do Panamá','archivo importado.':'arquivo importado.','No mide asistencia al mandato actual.':'Não mede presença no mandato atual.','Segundo Debate al Proyecto de Ley No.':'Segundo debate do Projeto de Lei nº',
  'Votaciones del archivo':'Votações do arquivo','No pudimos cargar el archivo. Vuelve a intentar recargando esta página.':'Não foi possível carregar o arquivo. Recarregue a página para tentar novamente.','No hay un archivo de votaciones vinculado a este perfil. Para cargos ejecutivos, este indicador no aplica.':'Não há arquivo de votações vinculado a este perfil. Este indicador não se aplica a cargos executivos.','Planilla: monto importado de Espacio Cívico, sin fecha de corte documentada. Corresponde al despacho, no al salario ni al patrimonio de la persona.':'Folha de pagamento importada do Espacio Cívico sem data de corte documentada. O valor pertence ao gabinete, não ao salário ou ao patrimônio da pessoa.','Consultar monto en la fuente':'Consultar valor na fonte','Resumen extraído automáticamente del documento. Comprueba el original antes de citarlo.':'Resumo extraído automaticamente do documento. Confira o original antes de citá-lo.','La falta de un documento aquí no demuestra que la persona no lo haya presentado.':'A ausência de um documento aqui não demonstra que a pessoa deixou de apresentá-lo.',
  'Cargo y circunscripción. Registro del directorio:':'Cargo e circunscrição. Registro do diretório:','Biografía, comisiones y declaraciones. La importación no conserva una fecha de corte pública; los valores pueden haber cambiado.':'Biografia, comissões e declarações. A importação não preserva uma data de corte pública, por isso os valores podem ter mudado.','Sin fechas disponibles.':'Sem datas disponíveis.','No hay enlace individual a acta en la importación.':'A importação não contém um link individual para a ata.','cuentas':'contas','Más perfiles':'Mais perfis',
  'Cuenta con una licenciatura en Ingeniería en Sistemas de la Universidad Latina, Ingenería Eléctrica de la Universidad Tecnológica de Panamá y una maestría en Administración de Negocio de la Universidad Latina. En su trayectoria profesional, ha sido gerente de operaciones de Electra Noreste, gerente en Grupo Melo y gerente de operaciones de ETESA.':'Possui graduação em Engenharia de Sistemas pela Universidad Latina, graduação em Engenharia Elétrica pela Universidad Tecnológica de Panamá e mestrado em Administração de Empresas pela Universidad Latina. Sua experiência profissional inclui os cargos de gerente de operações da Electra Noreste, gerente do Grupo Melo e gerente de operações da ETESA.'
  ,'Archivo':'Arquivo','legislativo':'legislativo','Relaciones Exteriores':'Relações Exteriores','Asuntos Municipales':'Assuntos Municipais','Asuntos Agropecuarios':'Assuntos Agropecuários','Asuntos Indígenas':'Assuntos Indígenas','Comercio y Asuntos Económicos':'Comércio e Assuntos Econômicos','Comunicación y Transporte':'Comunicação e Transporte','Credenciales, Reglamento, Ética Parlamentaria y Asuntos Judiciales':'Credenciais, Regimento, Ética Parlamentar e Assuntos Judiciais','Economía y Finanzas':'Economia e Finanças','Educación, Cultura y Deportes':'Educação, Cultura e Esportes','Gobierno, Justicia y Asuntos Constitucionales':'Governo, Justiça e Assuntos Constitucionais','Infraestructura Pública y Asuntos del Canal':'Infraestrutura Pública e Assuntos do Canal','Mujer, Niñez, Juventud y Familia':'Mulher, Infância, Juventude e Família','Población, Ambiente y Desarrollo':'População, Meio Ambiente e Desenvolvimento','Presupuesto':'Orçamento','Trabajo, Salud y Desarrollo Social':'Trabalho, Saúde e Desenvolvimento Social'
 }
};

Object.assign(copy.en,{'Ver directorio':'View directory','Consultar registro legislativo':'View legislative record','Ver noticias y publicaciones':'View news and posts','Consultar publicaciones':'View posts','Noticias · publicaciones':'News · posts','Todo':'All','Tipo de actividad':'Activity type','Cargando actividad…':'Loading activity…','Cargando votaciones…':'Loading votes…','Anteriores':'Previous','Siguientes':'Next','Consultar reporte oficial':'View official report','Consultar original':'View original','Documento de propuestas':'Proposal document','Compromisos publicados':'Published commitments','El documento incluye indicadores.':'The document includes indicators.','El documento no incluye indicadores identificados.':'No indicators were identified in the document.','Los compromisos no acreditan resultados de gestión.':'Commitments do not establish delivered results.','Explorar Panamá':'Explore Panama','Explorar territorios':'Explore territories','Territorios':'Territories','Comisiones':'Committees','Provincias':'Provinces','Circuitos':'Electoral districts','Circuitos electorales':'Electoral districts','Distritos':'Administrative districts','No hay publicaciones recogidas en esta categoría.':'No collected posts in this category.','Fecha original de publicación. Las noticias enlazan al medio; las publicaciones al autor. El archivo social conserva contenido histórico y no acredita actividad actual.':'Original publication date. News links to the publisher; posts link to the author. The social archive contains historical content and does not establish current activity.'});
Object.assign(copy.pt,{'Ver directorio':'Ver diretório','Consultar registro legislativo':'Consultar registro legislativo','Ver noticias y publicaciones':'Ver notícias e publicações','Consultar publicaciones':'Consultar publicações','Noticias · publicaciones':'Notícias · publicações','Todo':'Tudo','Tipo de actividad':'Tipo de atividade','Cargando actividad…':'Carregando atividade…','Cargando votaciones…':'Carregando votos…','Anteriores':'Anteriores','Siguientes':'Seguintes','Consultar reporte oficial':'Consultar relatório oficial','Consultar original':'Consultar original','Documento de propuestas':'Documento de propostas','Compromisos publicados':'Compromissos publicados','El documento incluye indicadores.':'O documento inclui indicadores.','El documento no incluye indicadores identificados.':'Nenhum indicador foi identificado no documento.','Los compromisos no acreditan resultados de gestión.':'Os compromissos não comprovam resultados de gestão.','Explorar Panamá':'Explorar Panamá','Explorar territorios':'Explorar territórios','Territorios':'Territórios','Comisiones':'Comissões','Provincias':'Províncias','Circuitos':'Circuitos eleitorais','Circuitos electorales':'Circuitos eleitorais','Distritos':'Distritos administrativos','No hay publicaciones recogidas en esta categoría.':'Nenhuma publicação recolhida nesta categoria.','Fecha original de publicación. Las noticias enlazan al medio; las publicaciones al autor. El archivo social conserva contenido histórico y no acredita actividad actual.':'Data original de publicação. Notícias apontam para o veículo; publicações apontam para o autor. O arquivo social contém conteúdo histórico e não comprova atividade atual.'});
Object.assign(copy.en,{
 'Independiente':'Independent','Actividad':'Activity','Buscar':'Search','vinculados en el directorio':'linked in the directory','No hay perfiles registrados en este cargo.':'No profiles are recorded for this office.',
 'Encuentra las personas vinculadas a cada comisión registrada, en todos los cargos del directorio.':'Find people linked to each recorded committee across every office in the directory.',
 'Encuentra las personas vinculadas a cada partido o agrupación, en todos los cargos del directorio.':'Find people linked to each party or group across every office in the directory.',
 'Encuentra las personas vinculadas a cada territorio, en todos los cargos del directorio.':'Find people linked to each territory across every office in the directory.',
 'La agrupación corresponde al registro del directorio. Los cambios de afiliación requieren una fuente y fecha propias.':'Affiliation reflects the directory record. Changes of affiliation require their own source and date.',
 'Membresía importada de Espacio Cívico. El período no está publicado en este registro.':'Membership imported from Espacio Cívico. This record does not publish a term.',
 'Consultar cobertura':'View coverage',
 'Los circuitos electorales y los distritos administrativos son ámbitos distintos. Solo se muestran asociaciones documentadas en el directorio. Mapas: Instituto Geográfico Nacional Tommy Guardia, a través de ArcGIS.':'Electoral districts and administrative districts are different jurisdictions. Only documented directory associations are shown. Maps: Instituto Geográfico Nacional Tommy Guardia, via ArcGIS.'
});
Object.assign(copy.pt,{
 'Independiente':'Independente','Actividad':'Atividade','Buscar':'Buscar','vinculados en el directorio':'vinculados no diretório','No hay perfiles registrados en este cargo.':'Nenhum perfil registrado neste cargo.',
 'Encuentra las personas vinculadas a cada comisión registrada, en todos los cargos del directorio.':'Encontre as pessoas vinculadas a cada comissão registrada, em todos os cargos do diretório.',
 'Encuentra las personas vinculadas a cada partido o agrupación, en todos los cargos del directorio.':'Encontre as pessoas vinculadas a cada partido ou grupo, em todos os cargos do diretório.',
 'Encuentra las personas vinculadas a cada territorio, en todos los cargos del directorio.':'Encontre as pessoas vinculadas a cada território, em todos os cargos do diretório.',
 'La agrupación corresponde al registro del directorio. Los cambios de afiliación requieren una fuente y fecha propias.':'A filiação corresponde ao registro do diretório. Mudanças de filiação exigem fonte e data próprias.',
 'Membresía importada de Espacio Cívico. El período no está publicado en este registro.':'Participação importada de Espacio Cívico. O período não está publicado neste registro.',
 'Consultar cobertura':'Consultar cobertura',
 'Los circuitos electorales y los distritos administrativos son ámbitos distintos. Solo se muestran asociaciones documentadas en el directorio. Mapas: Instituto Geográfico Nacional Tommy Guardia, a través de ArcGIS.':'Os circuitos eleitorais e os distritos administrativos são jurisdições distintas. Apenas associações documentadas no diretório são exibidas. Mapas: Instituto Geográfico Nacional Tommy Guardia, via ArcGIS.'
});
Object.assign(copy.en,{
 'Proyectos y políticas':'Bills and policies','Proyecto':'Bill','Anteproyecto':'Draft bill','Ficha':'Record','Comprobado':'Checked','Cargando proyectos…':'Loading bills…','Cargar más':'Load more','Actividad legislativa':'Legislative activity',
 'Votaciones publicadas por la Asamblea Nacional. El título conserva la redacción del registro oficial; no acredita la aprobación final de una ley.':'Votes published by the National Assembly. Titles retain the wording of the official record; they do not establish final enactment of a law.',
 'Etapa y proponentes publicados por la Asamblea. La asociación con un perfil indica autoría registrada, no un voto a favor. La etapa se conserva tal como aparece en la fuente.':'Stage and proponents published by the Assembly. A profile association indicates recorded authorship, not a vote in favor. The stage is preserved as published in the source.',
 'Sin proyectos vinculados en las fichas recogidas. La cobertura continúa ampliándose.':'No linked bills in the collected records. Coverage continues to expand.',
 'Ver contenido original':'View original content','Leer publicación':'Read post','Fuente de nacimiento':'Birth-date source','Fuente de lugar de nacimiento':'Birthplace source','Fuente biográfica':'Biography source',
 'Consulta las fichas y sigue sus cambios de etapa.':'Browse the records and follow their stage changes.','Todos los proyectos':'All bills','Etapa publicada':'Published stage','Proponentes registrados':'Recorded proponents','Cambios observados':'Observed changes','Consultar ficha en la Asamblea':'View Assembly record',
 'Las fechas de cambios corresponden a la recogida de ORWELL. No son fechas de aprobación. El estado procede del seguimiento oficial; una votación o un tercer debate no acredita por sí solo una ley sancionada.':'Change dates reflect ORWELL collection dates. They are not approval dates. Status comes from official tracking; a vote or third debate alone does not establish an enacted law.',
 'Busca la ficha':'Find record','en el sistema oficial. Última comprobación:':'in the official system. Last checked:',
 'Actividad política':'Political activity','Noticias, publicaciones y registros legislativos, reunidos desde sus fuentes.':'News, posts, and legislative records collected from their sources.'
});
Object.assign(copy.pt,{
 'Proyectos y políticas':'Projetos e políticas','Proyecto':'Projeto','Anteproyecto':'Anteprojeto','Ficha':'Ficha','Comprobado':'Verificado','Cargando proyectos…':'Carregando projetos…','Cargar más':'Carregar mais','Actividad legislativa':'Atividade legislativa',
 'Votaciones publicadas por la Asamblea Nacional. El título conserva la redacción del registro oficial; no acredita la aprobación final de una ley.':'Votações publicadas pela Assembleia Nacional. O título preserva a redação do registro oficial; não comprova a aprovação final de uma lei.',
 'Etapa y proponentes publicados por la Asamblea. La asociación con un perfil indica autoría registrada, no un voto a favor. La etapa se conserva tal como aparece en la fuente.':'Etapa e proponentes publicados pela Assembleia. A associação a um perfil indica autoria registrada, não um voto a favor. A etapa é preservada como aparece na fonte.',
 'Sin proyectos vinculados en las fichas recogidas. La cobertura continúa ampliándose.':'Nenhum projeto vinculado nas fichas coletadas. A cobertura continua a crescer.',
 'Ver contenido original':'Ver conteúdo original','Leer publicación':'Ler publicação','Fuente de nacimiento':'Fonte da data de nascimento','Fuente de lugar de nacimiento':'Fonte do local de nascimento','Fuente biográfica':'Fonte biográfica',
 'Consulta las fichas y sigue sus cambios de etapa.':'Consulte as fichas e acompanhe as mudanças de etapa.','Todos los proyectos':'Todos os projetos','Etapa publicada':'Etapa publicada','Proponentes registrados':'Proponentes registrados','Cambios observados':'Mudanças observadas','Consultar ficha en la Asamblea':'Consultar ficha na Assembleia',
 'Las fechas de cambios corresponden a la recogida de ORWELL. No son fechas de aprobación. El estado procede del seguimiento oficial; una votación o un tercer debate no acredita por sí solo una ley sancionada.':'As datas de mudanças correspondem à coleta do ORWELL. Não são datas de aprovação. O estado vem do acompanhamento oficial; uma votação ou um terceiro debate, por si só, não comprova uma lei sancionada.',
 'Busca la ficha':'Busque a ficha','en el sistema oficial. Última comprobación:':'no sistema oficial. Última verificação:',
 'Actividad política':'Atividade política','Noticias, publicaciones y registros legislativos, reunidos desde sus fuentes.':'Notícias, publicações e registros legislativos reunidos a partir de suas fontes.'
});
Object.assign(copy.en,{'Proyectos':'Bills','perfiles':'profiles','redes':'networks','registros':'records','Secretaria General':'Secretary General','Secretaría General':'General Secretariat','Secretario General':'Secretary General','Presidente del partido':'Party chairman','Presidenta del partido':'Party chairwoman','Presidente de partido':'Party chairman','Presidenta de partido':'Party chairwoman'});
Object.assign(copy.pt,{'Proyectos':'Projetos','perfiles':'perfis','redes':'redes','registros':'registros','Secretaria General':'Secretária-geral','Secretaría General':'Secretaria-geral','Secretario General':'Secretário-geral','Presidente del partido':'Presidente do partido','Presidenta del partido':'Presidente do partido','Presidente de partido':'Presidente do partido','Presidenta de partido':'Presidente do partido'});
Object.assign(copy.en,{'Su hoja de vida electoral registra una licenciatura en Economía y una gestión anterior como gobernadora entre 2009 y 2014. Fue juramentada gobernadora de Chiriquí el 3 de julio de 2024.':'Her electoral résumé records a bachelor’s degree in Economics and a previous term as governor from 2009 to 2014. She was sworn in as governor of Chiriquí on July 3, 2024.'});
Object.assign(copy.pt,{'Su hoja de vida electoral registra una licenciatura en Economía y una gestión anterior como gobernadora entre 2009 y 2014. Fue juramentada gobernadora de Chiriquí el 3 de julio de 2024.':'Seu currículo eleitoral registra uma licenciatura em Economia e uma gestão anterior como governadora entre 2009 e 2014. Foi empossada governadora de Chiriquí em 3 de julho de 2024.'});
Object.assign(copy.en,{
 'Registro de fuentes institucionales':'Institutional source registry','Medios de noticias en el archivo':'News publishers in the archive','Plataformas y cuentas sociales':'Social platforms and accounts','Directorio de cuentas sociales':'Social account directory','Persona':'Person','Cuenta':'Account','Archivo':'Archive','publicaciones':'posts','perfiles públicos':'public profiles','noticias archivadas':'archived news articles','publicaciones sociales':'social posts','proyectos seguidos':'tracked bills','Visitar fuente ↗':'Visit source ↗','Medio':'Publisher','Noticias':'News','Más reciente':'Latest','Plataforma':'Platform','Cuentas':'Accounts','Publicaciones':'Posts',
 'Estos son los medios que aparecen actualmente en los datos. El nombre identifica al editor de la noticia; el enlace abre una nota original de ese medio.':'These are the publishers currently present in the data. The name identifies the news publisher; the link opens an original article from that outlet.',
 'Los autores sociales son las personas y cuentas del directorio; no son medios periodísticos. Los conteos describen el archivo disponible.':'Social authors are the people and accounts in the directory; they are not news publishers. Counts describe the available archive.',
 'Asamblea Nacional de Panamá':'National Assembly of Panama','Perfiles de diputados, votaciones electrónicas, reportes plenarios y seguimiento de proyectos de ley.':'Profiles of members, electronic votes, plenary reports, and bill tracking.','Ministerio de Gobierno':'Ministry of Government','Perfiles y nombramientos de gobernadores publicados por la institución.':'Governor profiles and appointments published by the institution.','Biografías, comisiones, hojas de vida, declaraciones y documentos públicos enlazados.':'Biographies, committees, résumés, declarations, and linked public documents.','Archivo histórico de publicaciones de cuentas identificadas. Conserva la fecha y el enlace del contenido original.':'Historical archive of posts from identified accounts. It preserves the original date and content link.','Descubrimiento de noticias por nombre. Cada resultado enlaza al medio que publicó la nota.':'News discovery by name. Each result links to the outlet that published the article.','Geometrías cartográficas de provincias y comarcas servidas a través de ArcGIS.':'Map geometry for provinces and comarcas served through ArcGIS.',
 'Actividad disponible para':'Activity available for','perfiles. Las cifras se calculan desde el registro en vivo y cambian al ingresar nuevas fuentes.':'profiles. Figures are calculated from the live registry and change as new sources are added.',
 'ORWELL reúne perfiles y registros públicos para facilitar su consulta. Cada fuente conserva su alcance; los vacíos permanecen visibles.':'ORWELL brings public profiles and records together for easier review. Each source keeps its own scope, and gaps remain visible.',
 'La última modificación del directorio indica cuándo se guardó su registro. No certifica que el cargo siga vigente. Las votaciones muestran la fecha de la sesión en UTC. Una importación sin fecha de corte se identifica como tal.':'The directory’s last-modified date shows when its record was saved. It does not certify that the office is still current. Votes show the session date in UTC. An import without a cutoff date is identified as such.',
 'Documentos y finanzas':'Documents and finances','Redes y actividad':'Social media and activity','Cobertura y correcciones':'Coverage and corrections',
 '“No documentado” significa que falta evidencia en esta aplicación. No significa cero, ausencia de actividad o incumplimiento. Los números del directorio describen sus perfiles, no un censo completo del gobierno. Consulta siempre la fuente antes de citar un dato.':'“Not documented” means this application lacks supporting evidence. It does not mean zero, no activity, or noncompliance. Directory figures describe its profiles rather than a complete government census. Always review the source before citing a fact.',
 'Los registros combinan la importación histórica y nuevos reportes públicos del sistema electrónico de la Asamblea Nacional, comprobados diariamente. Incluyen titulares y suplentes de diferentes períodos. Una fecha con voto registrado acredita actividad en ese archivo; no permite calcular por sí sola una tasa de asistencia.':'The records combine the historical import with new public reports from the National Assembly electronic system, checked daily. They include principal and alternate members from different terms. A date with a recorded vote establishes activity in that archive; by itself, it cannot be used to calculate an attendance rate.',
 'Los resúmenes extraídos automáticamente se distinguen del documento original. La planilla del despacho es un gasto de personal; no es el salario personal del diputado. El patrimonio declarado se mantiene separado de cualquier estimación de riqueza.':'Automatically extracted summaries are distinguished from the original document. Office payroll is a personnel expense; it is not the member’s personal salary. Declared assets remain separate from any wealth estimate.',
 'Las publicaciones se reutilizan del archivo de ORWELL Monitor, con su fecha original y enlace al autor. Su recogida histórica no acredita actividad reciente. Las noticias se deduplican por perfil y URL; ORWELL no genera el texto de las noticias.':'Posts are reused from the ORWELL Monitor archive with their original date and author link. Historical collection does not establish recent activity. News is deduplicated by profile and URL; ORWELL does not generate the text of news articles.',
 'Licenciado en Derecho y Ciencias Políticas. Fue alcalde de Río de Jesús entre 2019 y 2024 y cuenta con experiencia previa en administración pública y mecánica.':'He holds a degree in Law and Political Science. He served as mayor of Río de Jesús from 2019 to 2024 and has prior experience in public administration and mechanics.',
 'Emprendedor y alcalde del distrito de Panamá. Su ficha municipal documenta su formación y trayectoria profesional.':'Entrepreneur and mayor of the district of Panama. His municipal record documents his education and professional career.',
 'Administradora y empresaria. Fue diputada de la Asamblea Nacional y ocupó responsabilidades de liderazgo legislativo.':'Administrator and businesswoman. She served in the National Assembly and held legislative leadership responsibilities.',
 'Ingeniera agrónoma. Fue alcaldesa de San Miguelito, diputada en tres períodos y ministra de Vivienda.':'Agricultural engineer. She served as mayor of San Miguelito, as a member of the National Assembly for three terms, and as minister of Housing.',
 'Exdiputado y presidente de la Asamblea Nacional durante el período 2010–2011.':'Former member and president of the National Assembly during the 2010–2011 term.',
 'Abogado, candidato presidencial en 2019 y 2024 y dirigente del Movimiento Otro Camino.':'Lawyer, presidential candidate in 2019 and 2024, and leader of Movimiento Otro Camino.'
});
Object.assign(copy.pt,{
 'Registro de fuentes institucionales':'Registro de fontes institucionais','Medios de noticias en el archivo':'Veículos de notícias no arquivo','Plataformas y cuentas sociales':'Plataformas e contas sociais','Directorio de cuentas sociales':'Diretório de contas sociais','Persona':'Pessoa','Cuenta':'Conta','Archivo':'Arquivo','publicaciones':'publicações','perfiles públicos':'perfis públicos','noticias archivadas':'notícias arquivadas','publicaciones sociales':'publicações sociais','proyectos seguidos':'projetos acompanhados','Visitar fuente ↗':'Visitar fonte ↗','Medio':'Veículo','Noticias':'Notícias','Más reciente':'Mais recente','Plataforma':'Plataforma','Cuentas':'Contas','Publicaciones':'Publicações',
 'Estos son los medios que aparecen actualmente en los datos. El nombre identifica al editor de la noticia; el enlace abre una nota original de ese medio.':'Estes são os veículos atualmente presentes nos dados. O nome identifica o editor da notícia; o link abre uma matéria original desse veículo.',
 'Los autores sociales son las personas y cuentas del directorio; no son medios periodísticos. Los conteos describen el archivo disponible.':'Os autores sociais são as pessoas e contas do diretório; não são veículos jornalísticos. As contagens descrevem o arquivo disponível.',
 'Asamblea Nacional de Panamá':'Assembleia Nacional do Panamá','Perfiles de diputados, votaciones electrónicas, reportes plenarios y seguimiento de proyectos de ley.':'Perfis de deputados, votações eletrônicas, relatórios plenários e acompanhamento de projetos de lei.','Ministerio de Gobierno':'Ministério do Governo','Perfiles y nombramientos de gobernadores publicados por la institución.':'Perfis e nomeações de governadores publicados pela instituição.','Biografías, comisiones, hojas de vida, declaraciones y documentos públicos enlazados.':'Biografias, comissões, currículos, declarações e documentos públicos vinculados.','Archivo histórico de publicaciones de cuentas identificadas. Conserva la fecha y el enlace del contenido original.':'Arquivo histórico de publicações de contas identificadas. Preserva a data e o link do conteúdo original.','Descubrimiento de noticias por nombre. Cada resultado enlaza al medio que publicó la nota.':'Descoberta de notícias por nome. Cada resultado aponta para o veículo que publicou a matéria.','Geometrías cartográficas de provincias y comarcas servidas a través de ArcGIS.':'Geometrias cartográficas de províncias e comarcas servidas por meio do ArcGIS.',
 'Actividad disponible para':'Atividade disponível para','perfiles. Las cifras se calculan desde el registro en vivo y cambian al ingresar nuevas fuentes.':'perfis. Os números são calculados a partir do registro ao vivo e mudam com a entrada de novas fontes.',
 'ORWELL reúne perfiles y registros públicos para facilitar su consulta. Cada fuente conserva su alcance; los vacíos permanecen visibles.':'O ORWELL reúne perfis e registros públicos para facilitar a consulta. Cada fonte mantém seu próprio alcance, e as lacunas permanecem visíveis.',
 'La última modificación del directorio indica cuándo se guardó su registro. No certifica que el cargo siga vigente. Las votaciones muestran la fecha de la sesión en UTC. Una importación sin fecha de corte se identifica como tal.':'A última modificação do diretório mostra quando o registro foi salvo. Ela não certifica que o cargo ainda esteja vigente. As votações mostram a data da sessão em UTC. Uma importação sem data de corte é identificada como tal.',
 'Documentos y finanzas':'Documentos e finanças','Redes y actividad':'Redes sociais e atividade','Cobertura y correcciones':'Cobertura e correções',
 '“No documentado” significa que falta evidencia en esta aplicación. No significa cero, ausencia de actividad o incumplimiento. Los números del directorio describen sus perfiles, no un censo completo del gobierno. Consulta siempre la fuente antes de citar un dato.':'“Não documentado” significa que faltam evidências neste aplicativo. Não significa zero, ausência de atividade ou descumprimento. Os números do diretório descrevem seus perfis, não um censo completo do governo. Consulte sempre a fonte antes de citar um dado.',
 'Los registros combinan la importación histórica y nuevos reportes públicos del sistema electrónico de la Asamblea Nacional, comprobados diariamente. Incluyen titulares y suplentes de diferentes períodos. Una fecha con voto registrado acredita actividad en ese archivo; no permite calcular por sí sola una tasa de asistencia.':'Os registros combinam a importação histórica com novos relatórios públicos do sistema eletrônico da Assembleia Nacional, verificados diariamente. Incluem titulares e suplentes de diferentes mandatos. Uma data com voto registrado comprova atividade nesse arquivo; por si só, não permite calcular uma taxa de presença.',
 'Los resúmenes extraídos automáticamente se distinguen del documento original. La planilla del despacho es un gasto de personal; no es el salario personal del diputado. El patrimonio declarado se mantiene separado de cualquier estimación de riqueza.':'Os resumos extraídos automaticamente são diferenciados do documento original. A folha do gabinete é uma despesa de pessoal; não é o salário pessoal do deputado. O patrimônio declarado permanece separado de qualquer estimativa de riqueza.',
 'Las publicaciones se reutilizan del archivo de ORWELL Monitor, con su fecha original y enlace al autor. Su recogida histórica no acredita actividad reciente. Las noticias se deduplican por perfil y URL; ORWELL no genera el texto de las noticias.':'As publicações são reutilizadas do arquivo do ORWELL Monitor, com a data original e o link do autor. A coleta histórica não comprova atividade recente. As notícias são deduplicadas por perfil e URL; o ORWELL não gera o texto das notícias.',
 'Licenciado en Derecho y Ciencias Políticas. Fue alcalde de Río de Jesús entre 2019 y 2024 y cuenta con experiencia previa en administración pública y mecánica.':'Formado em Direito e Ciências Políticas. Foi prefeito de Río de Jesús entre 2019 e 2024 e tem experiência anterior em administração pública e mecânica.',
 'Emprendedor y alcalde del distrito de Panamá. Su ficha municipal documenta su formación y trayectoria profesional.':'Empreendedor e prefeito do distrito do Panamá. Sua ficha municipal documenta sua formação e trajetória profissional.',
 'Administradora y empresaria. Fue diputada de la Asamblea Nacional y ocupó responsabilidades de liderazgo legislativo.':'Administradora e empresária. Foi deputada da Assembleia Nacional e exerceu responsabilidades de liderança legislativa.',
 'Ingeniera agrónoma. Fue alcaldesa de San Miguelito, diputada en tres períodos y ministra de Vivienda.':'Engenheira agrônoma. Foi prefeita de San Miguelito, deputada em três mandatos e ministra da Habitação.',
 'Exdiputado y presidente de la Asamblea Nacional durante el período 2010–2011.':'Ex-deputado e presidente da Assembleia Nacional durante o período de 2010–2011.',
 'Abogado, candidato presidencial en 2019 y 2024 y dirigente del Movimiento Otro Camino.':'Advogado, candidato à presidência em 2019 e 2024 e dirigente do Movimiento Otro Camino.'
});
function translateDynamic(value:string,lang:'en'|'pt'){
 const months=lang==='en'?{enero:'January',febrero:'February',marzo:'March',abril:'April',mayo:'May',junio:'June',julio:'July',agosto:'August',septiembre:'September',octubre:'October',noviembre:'November',diciembre:'December'}:{enero:'janeiro',febrero:'fevereiro',marzo:'março',abril:'abril',mayo:'maio',junio:'junho',julio:'julho',agosto:'agosto',septiembre:'setembro',octubre:'outubro',noviembre:'novembro',diciembre:'dezembro'};
 const date=value.match(/^(\d{1,2}) de ([a-záéíóú]+) de (\d{4})$/i);if(date){const month=months[date[2].toLowerCase() as keyof typeof months];if(month)return lang==='en'?`${month} ${date[1]}, ${date[3]}`:`${date[1]} de ${month} de ${date[3]}`}
 const shortMonths=lang==='en'?{ene:'Jan',feb:'Feb',mar:'Mar',abr:'Apr',may:'May',jun:'Jun',jul:'Jul',ago:'Aug',sep:'Sep',sept:'Sep',oct:'Oct',nov:'Nov',dic:'Dec'}:{ene:'jan',feb:'fev',mar:'mar',abr:'abr',may:'mai',jun:'jun',jul:'jul',ago:'ago',sep:'set',sept:'set',oct:'out',nov:'nov',dic:'dez'};
 const shortDate=value.match(/^(\d{1,2}) (ene|feb|mar|abr|may|jun|jul|ago|sep|sept|oct|nov|dic) (\d{4})$/i);if(shortDate){const month=shortMonths[shortDate[2].toLowerCase() as keyof typeof shortMonths];if(month)return lang==='en'?`${month} ${shortDate[1]}, ${shortDate[3]}`:`${shortDate[1]} ${month} ${shortDate[3]}`}
 const rules=lang==='en'?[ [/^(\d+) perfiles$/, '$1 profiles'], [/^(\d+) cuentas$/, '$1 accounts'], [/^(\d+) redes$/, '$1 networks'], [/^(\d+) de (\d+) perfiles$/, '$1 of $2 profiles'], [/^Mostrar (\d+) registros más$/, 'Show $1 more records'], [/^Más perfiles · (.+)$/, 'More profiles · $1'], [/^Volver a (.+)$/, 'Back to $1'], [/^Voto vinculado a (.+)$/, 'Vote linked to $1'] ]:[ [/^(\d+) perfiles$/, '$1 perfis'], [/^(\d+) cuentas$/, '$1 contas'], [/^(\d+) redes$/, '$1 redes'], [/^(\d+) de (\d+) perfiles$/, '$1 de $2 perfis'], [/^Mostrar (\d+) registros más$/, 'Mostrar mais $1 registros'], [/^Más perfiles · (.+)$/, 'Mais perfis · $1'], [/^Volver a (.+)$/, 'Voltar para $1'], [/^Voto vinculado a (.+)$/, 'Voto vinculado a $1'] ];
 for(const [pattern,replacement] of rules as [RegExp,string][]){if(pattern.test(value))return value.replace(pattern,replacement)}
 return value;
}

function translateText(raw:string,lang:'en'|'pt'){
 const clean=raw.trim();if(!clean)return raw;
 let translated=copy[lang][clean]||translateDynamic(clean,lang);
 if(translated===clean){for(const source of Object.keys(copy[lang]).sort((a,b)=>b.length-a.length)){if(source.length<5)continue;const escaped=source.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');translated=translated.replace(new RegExp(`(?<![\\p{L}\\p{N}])${escaped}(?![\\p{L}\\p{N}])`,'gu'),copy[lang][source])}}
 return translated===clean?raw:raw.replace(clean,translated);
}

function translateTree(root:Node,lang:'en'|'pt'){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=root.nodeType===Node.TEXT_NODE?[root as Text]:[];
 while(walker.nextNode())nodes.push(walker.currentNode as Text);
 nodes.forEach(node=>{if(!node.parentElement?.closest('script,style,textarea,[data-no-translate]'))node.nodeValue=translateText(node.nodeValue||'',lang)});
 if(root instanceof Element){[root,...Array.from(root.querySelectorAll('*'))].forEach(el=>{for(const attr of ['placeholder','aria-label','title']){const value=el.getAttribute(attr);if(value)el.setAttribute(attr,translateText(value,lang));}})}
}

export function LanguageRuntime(){
 useEffect(()=>{
  const saved=localStorage.getItem(storageKey);const lang:SiteLanguage=saved==='en'||saved==='pt'?saved:'es';document.documentElement.lang=lang;if(lang==='es')return;
  let observer:MutationObserver|undefined;let timer:number|undefined;
  const apply=()=>{timer=window.setTimeout(()=>{translateTree(document.body,lang);observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>translateTree(node,lang))));observer.observe(document.body,{childList:true,subtree:true});},350)};
  if(document.readyState==='complete')apply();else window.addEventListener('load',apply,{once:true});
  return()=>{window.removeEventListener('load',apply);if(timer)window.clearTimeout(timer);observer?.disconnect()};
 },[]);
 return null;
}

export function LanguageSwitcher({compact=false}:{compact?:boolean}){
 const lang=useSyncExternalStore(subscribeLanguage,readLanguage,readServerLanguage);
 return <div className={`language-switcher${compact?' language-switcher-compact':''}`} data-no-translate aria-label="Idioma"><span className="sr-only">Idioma</span>{(['es','en','pt'] as const).map(code=><button key={code} type="button" aria-pressed={lang===code} onClick={()=>{localStorage.setItem(storageKey,code);window.location.reload();}}>{code.toUpperCase()}</button>)}</div>;
}
