'use client';

import {useEffect, useState} from 'react';

export type SiteLanguage='es'|'en'|'pt';
const storageKey='orwell-panama-language';

const copy:Record<'en'|'pt',Record<string,string>>={
 en:{
  'Panamá':'Panama','Personas':'People','Cargos':'Offices','Partidos':'Parties','Fuentes':'Sources','Perfil':'Profile','Trayectoria':'Career','Votaciones':'Votes','Propuestas':'Proposals','Finanzas':'Finances','Redes':'Social','Comparar':'Compare','Políticos':'Politicians','Destacados':'Featured','Noticias':'News','Oficinas de Gobierno':'Public offices','Política':'Politics',
  'Buscar un nombre':'Search by name','Buscar políticos':'Search politicians','Busca un nombre, partido o provincia':'Search a name, party, or province','Borrar búsqueda':'Clear search','Menú de navegación':'Navigation menu','Menú de usuario':'User menu','Modo claro':'Light mode','Modo oscuro':'Dark mode','Perfil / Admin':'Profile / Admin','Cerrar sesión':'Sign out',
  'Cargo':'Office','Provincia':'Province','Circuito':'District','Ámbito':'Jurisdiction','Partido / agrupación':'Party / affiliation','Ficha institucional':'Official profile','Fuente oficial':'Official source','Volver al directorio':'Back to directory','Volver a Panamá':'Back to Panama','Todos los partidos':'All parties','Ver todos':'View all','Sitio oficial':'Official site','Institución de origen':'Source institution','Leer metodología':'Read methodology','Consultar metodología':'View methodology','Fuentes y metodología':'Sources and methodology',
  'Perfil profesional':'Professional profile','La ficha':'Profile record','Trayectoria y elecciones':'Career and elections','Documentos públicos':'Public documents','Comisiones registradas':'Recorded committees','El contexto importa':'Context matters','Documentos':'Documents','Nacimiento':'Birth date','Ciudadanía':'Citizenship','Salario personal':'Personal salary','Patrimonio declarado':'Declared assets','Archivo legislativo':'Legislative archive','Votos registrados':'Recorded votes','votos registrados':'recorded votes','Fechas con participación':'Dates with participation','fechas con votos':'voting dates','Última fecha del archivo':'Latest archive date','Últimos registros':'Latest records','Votos por año':'Votes by year','A favor':'In favor','En contra':'Against','Abstención':'Abstention',
  'Cargo registrado':'Recorded office','Fecha de nacimiento':'Date of birth','Lugar de nacimiento':'Place of birth','Suplente registrado':'Recorded alternate','No documentado':'Not documented','No documentada':'Not documented','Sin documentar':'Not documented','No consta':'Not available','No calculado':'Not calculated','Sin documentos enlazados.':'No linked documents.','Sin cuentas registradas.':'No recorded accounts.','Biografía pendiente de documentar.':'Biography pending documentation.','La biografía aún no está documentada en este perfil.':'The biography has not yet been documented in this profile.','Sin archivo legislativo vinculado.':'No linked legislative archive.','No hay documentos adjuntos.':'No attached documents.','Sin comisiones documentadas.':'No documented committees.',
  'Cuenta identificada':'Account identified','Identidad probable':'Likely identity','Publicaciones sin conectar':'Posts not connected','Actividad reciente':'Recent activity','Redes sociales':'Social media','Publicaciones y frecuencia':'Posts and frequency','Última publicación: sin datos':'Latest post: no data','Identificada en directorio':'Identified in directory','cuentas registradas':'recorded accounts',
  'Remuneración y patrimonio':'Compensation and assets','Planilla de despacho registrada':'Recorded office payroll','Patrimonio neto declarado':'Declared net worth','Patrimonio neto estimado':'Estimated net worth','Evidencia disponible':'Available evidence','Propuestas y formación':'Proposals and education','Fuentes y cobertura':'Sources and coverage','Archivo de la Asamblea Nacional':'National Assembly archive','Perfil y documentos':'Profile and documents','Metodología':'Methodology',
  'Propuesta Política':'Policy proposal','Plan de Gobierno':'Government plan','Ver PDF ↗':'View PDF ↗','Temas Prioritarios':'Priority issues','Áreas Estratégicas':'Strategic areas','Promesas Clave':'Key promises','Tiene indicadores':'Includes indicators','Perfil Profesional':'Professional profile','Educación':'Education','Experiencia Laboral':'Work experience','Cargos Políticos':'Political offices','Título no especificado':'Degree not specified','Cargo no especificado':'Office not specified','Declaración de Intereses':'Declaration of interests','Intereses Declarados':'Declared interests','Empresas':'Companies','Membresías':'Memberships','Fuentes Ingreso':'Income sources','Actividades Comerciales':'Business activities','Fuentes de Ingreso':'Sources of income','Parientes en Gobierno':'Relatives in government','Conflictos Declarados':'Declared conflicts','Declaración Patrimonial':'Asset declaration','Patrimonio Declarado':'Declared assets','Patrimonio Neto':'Net worth','Inmuebles':'Properties','Vehículos':'Vehicles','Cuentas':'Accounts','Deudas':'Debts','Bienes Inmuebles':'Real estate','Cuentas Bancarias':'Bank accounts','Inversiones':'Investments','Desglose de Votación':'Vote breakdown','Tendencia de Votación':'Voting trend','Sin datos de tendencia disponibles':'No voting-trend data available','Buscar proyecto o pregunta':'Search project or question','Ver pregunta':'View question',
  'Registro legislativo':'Legislative record','Registro de suplencia.':'Alternate-member record.','Vínculo y período pendientes de validación.':'Link and term pending validation.','Directorio':'Directory','Cobertura del directorio':'Directory coverage','Espacio Cívico · documentos públicos':'Espacio Cívico · public documents','Directorio de personas públicas':'Public officials directory','Asamblea Nacional':'National Assembly',
  'Resultados electorales y cambios de partido: sin una serie verificada en esta ficha.':'Election results and party changes: no verified series is available in this profile.','Este vínculo importado no acredita el mandato actual. Las sesiones con voto registrado no equivalen a una tasa de asistencia.':'This imported link does not establish the current term. Sessions with a recorded vote are not an attendance rate.','Importación histórica. Abre una votación para consultar su pregunta; no se infiere el resultado de una ley a partir de un voto individual.':'Historical import. Open a vote to view its question; the outcome of a law cannot be inferred from one individual vote.','Notas sobre participación, afinidad y rankings':'Notes on participation, alignment, and rankings',
  'Accede a las cuentas identificadas en el directorio. La actividad reciente aún no está conectada a esta ficha.':'Open the accounts identified in the directory. Recent activity is not yet connected to this profile.','No hay publicaciones importadas en esta aplicación. Cada publicación mostrará su plataforma, fecha y enlace de origen cuando se conecte el feed.':'No posts have been imported into this application. Each post will show its platform, date, and source link once the feed is connected.','No hay publicaciones importadas en esta aplicación. La red más activa y las últimas 5–10 publicaciones aparecerán cuando exista una fuente conectada y fechada. La prioridad de rastreo de una cuenta no mide su actividad.':'No posts have been imported into this application. The most active network and latest 5–10 posts will appear once a dated source is connected. An account’s tracking priority does not measure activity.',
  'Cada bloque distingue el registro del directorio, el archivo legislativo y los documentos de terceros. No se presenta una calificación global de la persona.':'Each section distinguishes directory records, legislative archives, and third-party documents. The site does not assign an overall rating to a person.','Identificación de cuentas, sin sincronización de publicaciones ni fecha de última actividad.':'Account identification, without post synchronization or a latest-activity date.','Extracción automática de documentos importados. Las propuestas son compromisos publicados, no resultados verificados.':'Automated extraction from imported documents. Proposals are published commitments, not verified outcomes.','No hay propuestas documentadas en esta ficha.':'No proposals are documented in this profile.',
  'La política tiene nombres.':'Politics has names.','Conoce su trayectoria.':'Know their record.','Perfiles públicos de Panamá. Consulta sus documentos y sigue el rastro de sus decisiones.':'Public profiles from Panama. Review their documents and follow the record of their decisions.','Explora':'Explore','Alcaldías':'Mayors','Perfiles en el directorio':'Profiles in the directory','Todos los cargos':'All offices','Todas las provincias':'All provinces','Limpiar':'Clear','Directorio de perfiles':'Profile directory','Nombre A–Z':'Name A–Z','Rango':'Rank','Añadido':'Added','No encontramos ese perfil':'We could not find that profile','Prueba otro nombre o elimina los filtros.':'Try another name or clear the filters.','Ver todos los perfiles':'View all profiles','Un registro útil también muestra lo que falta.':'A useful record also shows what is missing.','Cancelar comparación':'Cancel comparison',
  'Cargos públicos de Panamá':'Public offices in Panama','Explora los perfiles disponibles por función. Las cifras muestran la cobertura del directorio.':'Explore available profiles by role. Counts show the directory’s coverage.','Perfiles, lado a lado.':'Profiles, side by side.','Contrasta cargos y evidencia disponible. El volumen del archivo no mide el desempeño.':'Compare offices and available evidence. Archive volume does not measure performance.','Primer perfil':'First profile','Segundo perfil':'Second profile','Selecciona una persona':'Select a person','Ver perfil y fuentes':'View profile and sources','Selecciona dos perfiles distintos para abrir la comparación.':'Select two different profiles to open the comparison.',
  'El dato y su contexto.':'The data and its context.','Qué significa cada fecha':'What each date means','Redes y verificación':'Social accounts and verification','Documentos de terceros':'Third-party documents','Vacíos y correcciones':'Gaps and corrections','Pregunta sometida a votación':'Question put to a vote','Resultado de esta pregunta':'Result of this question','Aprobada':'Approved','Rechazada':'Rejected',
  'Datos de la':'Data from the','Este directorio es un proyecto de monitoreo cívico independiente. Las cuentas de redes sociales han sido verificadas mediante búsquedas públicas y fuentes oficiales.':'This directory is an independent civic-monitoring project. Social accounts have been verified through public searches and official sources.'
 },
 pt:{
  'Panamá':'Panamá','Personas':'Pessoas','Cargos':'Cargos','Partidos':'Partidos','Fuentes':'Fontes','Perfil':'Perfil','Trayectoria':'Trajetória','Votaciones':'Votações','Propuestas':'Propostas','Finanzas':'Finanças','Redes':'Redes','Comparar':'Comparar','Políticos':'Políticos','Destacados':'Destaques','Noticias':'Notícias','Oficinas de Gobierno':'Cargos públicos','Política':'Política',
  'Buscar un nombre':'Buscar por nome','Buscar políticos':'Buscar políticos','Busca un nombre, partido o provincia':'Busque um nome, partido ou província','Borrar búsqueda':'Limpar busca','Menú de navegación':'Menu de navegação','Menú de usuario':'Menu do usuário','Modo claro':'Modo claro','Modo oscuro':'Modo escuro','Perfil / Admin':'Perfil / Admin','Cerrar sesión':'Sair',
  'Cargo':'Cargo','Provincia':'Província','Circuito':'Distrito','Ámbito':'Âmbito','Partido / agrupación':'Partido / grupo','Ficha institucional':'Perfil institucional','Fuente oficial':'Fonte oficial','Volver al directorio':'Voltar ao diretório','Volver a Panamá':'Voltar ao Panamá','Todos los partidos':'Todos os partidos','Ver todos':'Ver todos','Sitio oficial':'Site oficial','Institución de origen':'Instituição de origem','Leer metodología':'Ler metodologia','Consultar metodología':'Consultar metodologia','Fuentes y metodología':'Fontes e metodologia',
  'Perfil profesional':'Perfil profissional','La ficha':'Ficha','Trayectoria y elecciones':'Trajetória e eleições','Documentos públicos':'Documentos públicos','Comisiones registradas':'Comissões registradas','El contexto importa':'O contexto importa','Documentos':'Documentos','Nacimiento':'Nascimento','Ciudadanía':'Cidadania','Salario personal':'Salário pessoal','Patrimonio declarado':'Patrimônio declarado','Archivo legislativo':'Arquivo legislativo','Votos registrados':'Votos registrados','votos registrados':'votos registrados','Fechas con participación':'Datas com participação','fechas con votos':'datas com votos','Última fecha del archivo':'Última data do arquivo','Últimos registros':'Registros recentes','Votos por año':'Votos por ano','A favor':'A favor','En contra':'Contra','Abstención':'Abstenção',
  'Cargo registrado':'Cargo registrado','Fecha de nacimiento':'Data de nascimento','Lugar de nacimiento':'Local de nascimento','Suplente registrado':'Suplente registrado','No documentado':'Não documentado','No documentada':'Não documentada','Sin documentar':'Não documentado','No consta':'Não informado','No calculado':'Não calculado','Sin documentos enlazados.':'Sem documentos vinculados.','Sin cuentas registradas.':'Sem contas registradas.','Biografía pendiente de documentar.':'Biografia pendente de documentação.','La biografía aún no está documentada en este perfil.':'A biografia ainda não foi documentada neste perfil.','Sin archivo legislativo vinculado.':'Sem arquivo legislativo vinculado.','No hay documentos adjuntos.':'Não há documentos anexados.','Sin comisiones documentadas.':'Sem comissões documentadas.',
  'Cuenta identificada':'Conta identificada','Identidad probable':'Identidade provável','Publicaciones sin conectar':'Publicações não conectadas','Actividad reciente':'Atividade recente','Redes sociales':'Redes sociais','Publicaciones y frecuencia':'Publicações e frequência','Última publicación: sin datos':'Última publicação: sem dados','Identificada en directorio':'Identificada no diretório','cuentas registradas':'contas registradas',
  'Remuneración y patrimonio':'Remuneração e patrimônio','Planilla de despacho registrada':'Folha do gabinete registrada','Patrimonio neto declarado':'Patrimônio líquido declarado','Patrimonio neto estimado':'Patrimônio líquido estimado','Evidencia disponible':'Evidência disponível','Propuestas y formación':'Propostas e formação','Fuentes y cobertura':'Fontes e cobertura','Archivo de la Asamblea Nacional':'Arquivo da Assembleia Nacional','Perfil y documentos':'Perfil e documentos','Metodología':'Metodologia',
  'Propuesta Política':'Proposta política','Plan de Gobierno':'Plano de governo','Ver PDF ↗':'Ver PDF ↗','Temas Prioritarios':'Temas prioritários','Áreas Estratégicas':'Áreas estratégicas','Promesas Clave':'Promessas principais','Tiene indicadores':'Inclui indicadores','Perfil Profesional':'Perfil profissional','Educación':'Educação','Experiencia Laboral':'Experiência profissional','Cargos Políticos':'Cargos políticos','Título no especificado':'Formação não especificada','Cargo no especificado':'Cargo não especificado','Declaración de Intereses':'Declaração de interesses','Intereses Declarados':'Interesses declarados','Empresas':'Empresas','Membresías':'Associações','Fuentes Ingreso':'Fontes de renda','Actividades Comerciales':'Atividades comerciais','Fuentes de Ingreso':'Fontes de renda','Parientes en Gobierno':'Parentes no governo','Conflictos Declarados':'Conflitos declarados','Declaración Patrimonial':'Declaração patrimonial','Patrimonio Declarado':'Patrimônio declarado','Patrimonio Neto':'Patrimônio líquido','Inmuebles':'Imóveis','Vehículos':'Veículos','Cuentas':'Contas','Deudas':'Dívidas','Bienes Inmuebles':'Bens imóveis','Cuentas Bancarias':'Contas bancárias','Inversiones':'Investimentos','Desglose de Votación':'Detalhamento da votação','Tendencia de Votación':'Tendência de votação','Sin datos de tendencia disponibles':'Sem dados disponíveis sobre tendência de votação','Buscar proyecto o pregunta':'Buscar projeto ou pergunta','Ver pregunta':'Ver pergunta',
  'Registro legislativo':'Registro legislativo','Registro de suplencia.':'Registro de suplência.','Vínculo y período pendientes de validación.':'Vínculo e período aguardando validação.','Directorio':'Diretório','Cobertura del directorio':'Cobertura do diretório','Espacio Cívico · documentos públicos':'Espacio Cívico · documentos públicos','Directorio de personas públicas':'Diretório de pessoas públicas','Asamblea Nacional':'Assembleia Nacional',
  'Resultados electorales y cambios de partido: sin una serie verificada en esta ficha.':'Resultados eleitorais e mudanças de partido: sem uma série verificada neste perfil.','Este vínculo importado no acredita el mandato actual. Las sesiones con voto registrado no equivalen a una tasa de asistencia.':'Este vínculo importado não comprova o mandato atual. Sessões com voto registrado não equivalem a uma taxa de presença.','Importación histórica. Abre una votación para consultar su pregunta; no se infiere el resultado de una ley a partir de un voto individual.':'Importação histórica. Abra uma votação para consultar a pergunta; o resultado de uma lei não pode ser inferido a partir de um voto individual.','Notas sobre participación, afinidad y rankings':'Notas sobre participação, alinhamento e classificações',
  'Accede a las cuentas identificadas en el directorio. La actividad reciente aún no está conectada a esta ficha.':'Acesse as contas identificadas no diretório. A atividade recente ainda não está conectada a este perfil.','No hay publicaciones importadas en esta aplicación. Cada publicación mostrará su plataforma, fecha y enlace de origen cuando se conecte el feed.':'Não há publicações importadas neste aplicativo. Cada publicação mostrará sua plataforma, data e link de origem quando o feed for conectado.','No hay publicaciones importadas en esta aplicación. La red más activa y las últimas 5–10 publicaciones aparecerán cuando exista una fuente conectada y fechada. La prioridad de rastreo de una cuenta no mide su actividad.':'Não há publicações importadas neste aplicativo. A rede mais ativa e as últimas 5–10 publicações aparecerão quando houver uma fonte conectada e datada. A prioridade de rastreamento de uma conta não mede sua atividade.',
  'Cada bloque distingue el registro del directorio, el archivo legislativo y los documentos de terceros. No se presenta una calificación global de la persona.':'Cada seção distingue o registro do diretório, o arquivo legislativo e documentos de terceiros. O site não atribui uma avaliação geral à pessoa.','Identificación de cuentas, sin sincronización de publicaciones ni fecha de última actividad.':'Identificação de contas, sem sincronização de publicações ou data da última atividade.','Extracción automática de documentos importados. Las propuestas son compromisos publicados, no resultados verificados.':'Extração automática de documentos importados. As propostas são compromissos publicados, não resultados verificados.','No hay propuestas documentadas en esta ficha.':'Não há propostas documentadas neste perfil.',
  'La política tiene nombres.':'A política tem nomes.','Conoce su trayectoria.':'Conheça suas trajetórias.','Perfiles públicos de Panamá. Consulta sus documentos y sigue el rastro de sus decisiones.':'Perfis públicos do Panamá. Consulte seus documentos e acompanhe o histórico de suas decisões.','Explora':'Explore','Alcaldías':'Prefeituras','Perfiles en el directorio':'Perfis no diretório','Todos los cargos':'Todos os cargos','Todas las provincias':'Todas as províncias','Limpiar':'Limpar','Directorio de perfiles':'Diretório de perfis','Nombre A–Z':'Nome A–Z','Rango':'Classificação','Añadido':'Adicionado','No encontramos ese perfil':'Não encontramos esse perfil','Prueba otro nombre o elimina los filtros.':'Tente outro nome ou remova os filtros.','Ver todos los perfiles':'Ver todos os perfis','Un registro útil también muestra lo que falta.':'Um registro útil também mostra o que está faltando.','Cancelar comparación':'Cancelar comparação',
  'Cargos públicos de Panamá':'Cargos públicos do Panamá','Explora los perfiles disponibles por función. Las cifras muestran la cobertura del directorio.':'Explore os perfis disponíveis por função. Os números mostram a cobertura do diretório.','Perfiles, lado a lado.':'Perfis lado a lado.','Contrasta cargos y evidencia disponible. El volumen del archivo no mide el desempeño.':'Compare cargos e evidências disponíveis. O volume do arquivo não mede o desempenho.','Primer perfil':'Primeiro perfil','Segundo perfil':'Segundo perfil','Selecciona una persona':'Selecione uma pessoa','Ver perfil y fuentes':'Ver perfil e fontes','Selecciona dos perfiles distintos para abrir la comparación.':'Selecione dois perfis diferentes para abrir a comparação.',
  'El dato y su contexto.':'Os dados e seu contexto.','Qué significa cada fecha':'O que cada data significa','Redes y verificación':'Redes e verificação','Documentos de terceros':'Documentos de terceiros','Vacíos y correcciones':'Lacunas e correções','Pregunta sometida a votación':'Questão submetida a votação','Resultado de esta pregunta':'Resultado desta questão','Aprobada':'Aprovada','Rechazada':'Rejeitada',
  'Datos de la':'Dados da','Este directorio es un proyecto de monitoreo cívico independiente. Las cuentas de redes sociales han sido verificadas mediante búsquedas públicas y fuentes oficiales.':'Este diretório é um projeto independente de monitoramento cívico. As contas de redes sociais foram verificadas por meio de buscas públicas e fontes oficiais.'
 }
};

function translateDynamic(value:string,lang:'en'|'pt'){
 const rules=lang==='en'?[ [/^(\d+) perfiles$/, '$1 profiles'], [/^(\d+) cuentas$/, '$1 accounts'], [/^(\d+) redes$/, '$1 networks'], [/^(\d+) de (\d+) perfiles$/, '$1 of $2 profiles'], [/^Mostrar (\d+) registros más$/, 'Show $1 more records'], [/^Más perfiles · (.+)$/, 'More profiles · $1'], [/^Volver a (.+)$/, 'Back to $1'], [/^Voto vinculado a (.+)$/, 'Vote linked to $1'] ]:[ [/^(\d+) perfiles$/, '$1 perfis'], [/^(\d+) cuentas$/, '$1 contas'], [/^(\d+) redes$/, '$1 redes'], [/^(\d+) de (\d+) perfiles$/, '$1 de $2 perfis'], [/^Mostrar (\d+) registros más$/, 'Mostrar mais $1 registros'], [/^Más perfiles · (.+)$/, 'Mais perfis · $1'], [/^Volver a (.+)$/, 'Voltar para $1'], [/^Voto vinculado a (.+)$/, 'Voto vinculado a $1'] ];
 for(const [pattern,replacement] of rules as [RegExp,string][]){if(pattern.test(value))return value.replace(pattern,replacement)}
 return value;
}

function translateText(raw:string,lang:'en'|'pt'){
 const clean=raw.trim();if(!clean)return raw;
 const translated=copy[lang][clean]||translateDynamic(clean,lang);
 return translated===clean?raw:raw.replace(clean,translated);
}

function translateTree(root:Node,lang:'en'|'pt'){
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=root.nodeType===Node.TEXT_NODE?[root as Text]:[];
 while(walker.nextNode())nodes.push(walker.currentNode as Text);
 nodes.forEach(node=>{if(!node.parentElement?.closest('script,style,textarea,[data-no-translate]'))node.nodeValue=translateText(node.nodeValue||'',lang)});
 if(root instanceof Element){[root,...Array.from(root.querySelectorAll('*'))].forEach(el=>{for(const attr of ['placeholder','aria-label','title']){const value=el.getAttribute(attr);if(value)el.setAttribute(attr,translateText(value,lang));}})}
}

export function LanguageRuntime(){
 useEffect(()=>{
  const saved=localStorage.getItem(storageKey);const lang:SiteLanguage=saved==='en'||saved==='pt'?saved:'es';document.documentElement.lang=lang;if(lang==='es')return;
  let observer:MutationObserver|undefined;let timer:number|undefined;
  const apply=()=>{timer=window.setTimeout(()=>{translateTree(document.body,lang);observer=new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>translateTree(node,lang))));observer.observe(document.body,{childList:true,subtree:true});},350)};
  if(document.readyState==='complete')apply();else window.addEventListener('load',apply,{once:true});
  return()=>{window.removeEventListener('load',apply);if(timer)window.clearTimeout(timer);observer?.disconnect()};
 },[]);
 return null;
}

export function LanguageSwitcher({compact=false}:{compact?:boolean}){
 const [lang,setLang]=useState<SiteLanguage>('es');
 useEffect(()=>{const saved=localStorage.getItem(storageKey);if(saved==='en'||saved==='pt')setLang(saved)},[]);
 return <div className={`language-switcher${compact?' language-switcher-compact':''}`} data-no-translate aria-label="Idioma"><span className="sr-only">Idioma</span>{(['es','en','pt'] as const).map(code=><button key={code} type="button" aria-pressed={lang===code} onClick={()=>{localStorage.setItem(storageKey,code);window.location.reload();}}>{code.toUpperCase()}</button>)}</div>;
}
