'use client';
import {useState} from 'react';
import {usePaginatedQuery} from 'convex/react';
import Link from 'next/link';
import {ArrowUpRight,Newspaper} from 'lucide-react';
import {api} from '../../../convex/_generated/api';
import type {Id} from '../../../convex/_generated/dataModel';
import {displayDate,platformIcon,PLATFORM_NAMES} from '@/lib/reference';
function embedUrl(source:string){try{const u=new URL(source);if(/(^|\.)instagram\.com$/.test(u.hostname)){const id=u.pathname.match(/^\/(p|reel)\/([A-Za-z0-9_-]+)/);if(id)return `https://www.instagram.com/${id[1]}/${id[2]}/embed/`;}if(/(^|\.)youtube\.com$/.test(u.hostname)||u.hostname==='youtu.be'){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.match(/\/shorts\/([\w-]+)/)?.[1];if(id&&/^[\w-]{11}$/.test(id))return `https://www.youtube-nocookie.com/embed/${id}`;}}catch{}return null;}
function ActivityMedia({imageUrl,mediaKind,sourceUrl,title}:{imageUrl?:string;mediaKind?:'image'|'video';sourceUrl:string;title:string}){const [failed,setFailed]=useState(false);const embed=embedUrl(sourceUrl);if(imageUrl&&!failed){if(mediaKind==='video'&&/\.mp4(?:\?|$)/i.test(imageUrl))return <video className="activity-image" controls preload="none" aria-label={title} onError={()=>setFailed(true)} src={imageUrl}/>;return <a className="activity-media-link" href={sourceUrl} target="_blank" rel="noreferrer"><img className="activity-image" loading="lazy" src={imageUrl} alt="" onError={()=>setFailed(true)}/></a>;}if(embed)return <iframe className="activity-embed" src={embed} title={title} loading="lazy" allow="encrypted-media; picture-in-picture" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/>;return <a className="activity-original" href={sourceUrl} target="_blank" rel="noreferrer">Ver contenido original <ArrowUpRight size={14}/></a>;}
export function ActivityFeed({politicianId,compact=false}:{politicianId?:Id<'politicians'>;compact?:boolean}){
 const [filter,setFilter]=useState<'all'|'news'|'social'>('all');const {results:rows,status,loadMore}=usePaginatedQuery(api.activity.paginated,{politicianId,kind:filter==='all'?undefined:filter},{initialNumItems:compact?6:24});
 const visible=rows?.filter(r=>filter==='all'||r.kind===filter);
 return <section className="activity-feed" data-section-id="recent-activity"><header><div><span className="eyebrow">Noticias · publicaciones</span><h2>Actividad reciente</h2></div><nav aria-label="Tipo de actividad">{[['all','Todo'],['news','Noticias'],['social','Redes']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id as 'all'|'news'|'social')}>{label}</button>)}</nav></header>{status==='LoadingFirstPage'?<p role="status">Cargando actividad…</p>:visible?.length?<div className="activity-grid">{visible.map(r=><article key={r._id} className="activity-card"><div className="activity-source">{r.sourceLogoUrl?<img className="activity-source-logo" src={r.sourceLogoUrl} alt={r.sourceName}/>:r.platform?<img src={platformIcon(r.platform)} alt="" width={20} height={20}/>:<Newspaper size={18}/>}<span>{r.platform?`${PLATFORM_NAMES[r.platform]||r.platform} · ${r.sourceName}`:r.sourceName}</span><time dateTime={new Date(r.publishedAt).toISOString()}>{displayDate(r.publishedAt)}</time></div><ActivityMedia imageUrl={r.imageUrl} mediaKind={r.mediaKind} sourceUrl={r.sourceUrl} title={r.title}/><a className="activity-title" href={r.sourceUrl} target="_blank" rel="noreferrer"><h3 data-no-translate>{r.title}</h3><ArrowUpRight size={17}/></a>{!compact&&r.summary&&r.summary!==r.title&&<details className="activity-caption"><summary>Leer publicación</summary><p data-no-translate>{r.summary}</p></details>}{!politicianId&&r.person&&<Link className="activity-person" href={`/politician/${r.person.externalId}`}>{r.person.name} · {r.person.role}</Link>}</article>)}</div>:<p className="record-empty">No hay publicaciones recogidas en esta categoría.</p>}{!compact&&status==='CanLoadMore'&&<button className="record-button" onClick={()=>loadMore(24)}>Cargar más</button>}<p className="source-note">Fecha original de publicación. Las noticias enlazan al medio; las publicaciones al autor. El archivo social conserva contenido histórico y no acredita actividad actual.</p></section>;
}
