'use client';
import {ArrowUpRight} from 'lucide-react';
import Link from 'next/link';
import {useState,useSyncExternalStore} from 'react';
import {getPartyLogoPath} from '@/lib/constants';
import type {ElectionResult} from '@/lib/elections';
import {electionParty} from '@/lib/election-party';
import {Portrait} from './Portrait';
import './elections.css';
const subscribe=(fn:()=>void)=>{window.addEventListener('storage',fn);return()=>window.removeEventListener('storage',fn);};
const language=()=>localStorage.getItem('orwell-panama-language')||'es';
const copy={scroll:['Desplázate horizontalmente para ver votos y fuentes','Scroll horizontally to see votes and sources','Role horizontalmente para ver votos e fontes'],title:['Elecciones de Panamá','Panama elections','Eleições do Panamá'],intro:['Resultados oficiales y las personas detrás de ellos.','Official results and the people behind them.','Resultados oficiais e as pessoas por trás deles.'],scope:['Elección general · 5 de mayo de 2024','General election · May 5, 2024','Eleição geral · 5 de maio de 2024'],note:['Este conjunto incluye únicamente diputados y alcaldes proclamados. No contiene todos los candidatos ni certifica el cargo actual. El porcentaje de diputados corresponde a los votos válidos del circuito publicados por el Tribunal Electoral; los porcentajes no deben sumarse en circuitos plurinominales.','This dataset includes proclaimed deputies and mayors only. It does not include every candidate or certify current office. Deputy percentages use the district’s valid votes published by the Electoral Tribunal; percentages must not be added together in multi-member districts.','Este conjunto inclui apenas deputados e prefeitos proclamados. Não inclui todos os candidatos nem certifica o cargo atual. Os percentuais de deputados usam os votos válidos do distrito publicados pelo Tribunal Electoral; não devem ser somados em distritos plurinominais.'],deputy:['Diputados','Deputies','Deputados'],mayor:['Alcaldes','Mayors','Prefeitos'],search:['Buscar nombre, partido o territorio','Search name, party, or territory','Buscar nome, partido ou território'],name:['Persona proclamada','Proclaimed winner','Pessoa proclamada'],territory:['Circuito / distrito','Electoral district / municipality','Distrito eleitoral / município'],party:['Partido en la elección','Party at the election','Partido na eleição'],votes:['Votos obtenidos','Votes obtained','Votos obtidos'],share:['% publicado','Published %','% publicado'],source:['Fuente oficial','Official source','Fonte oficial'],profile:['Ver perfil','View profile','Ver perfil'],results:['resultados','results','resultados'],none:['Sin resultados para esta búsqueda.','No results match this search.','Nenhum resultado para esta busca.'],snapshot:['Datos consultados el 8 de octubre de 2026.','Data retrieved on October 8, 2026.','Dados consultados em 8 de outubro de 2026.'],compare:['Comparar seleccionados','Compare selected','Comparar selecionados'],select:['Seleccionar para comparar','Select for comparison','Selecionar para comparar'],all:['Todos los territorios','All territories','Todos os territórios']} as const;
type Row=ElectionResult&{profile?:{id:string;portrait:string;name:string}};
export function ElectionWorkspace({rows}:{rows:Row[]}){
 const lang=useSyncExternalStore(subscribe,language,()=> 'es'),i=lang==='en'?1:lang==='pt'?2:0,t=(k:keyof typeof copy)=>copy[k][i];
 const [kind,setKind]=useState('deputy'),[search,setSearch]=useState(''),[territory,setTerritory]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const clean=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const visible=rows.filter(r=>r.kind===kind&&(!territory||r.territory===territory)&&clean([r.name,r.territory,r.province,r.party].join(' ')).includes(clean(search))).sort((a,b)=>b.votes-a.votes);
 return <main className="reference-world election-workspace" data-no-translate><div className="reference-wrap"><header><h1>{t('title')}</h1><p>{t('intro')}</p></header><aside className="election-note"><strong>{t('scope')}</strong><p>{t('note')}</p><a href="https://www.datosabiertos.gob.pa/organization/tribunal-electoral" target="_blank" rel="noreferrer"><img className="election-source-logo" src="/icons/official/tribunal-electoral-ined.png" alt="Tribunal Electoral e Instituto de Estudios Democráticos"/>Tribunal Electoral <ArrowUpRight size={15} aria-hidden="true"/></a><small>{t('snapshot')}</small></aside><div className="election-controls"><nav>{(['deputy','mayor'] as const).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setTerritory('');}}>{t(k)}</button>)}</nav><input type="search" aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/><select value={territory} aria-label={t('territory')} onChange={e=>setTerritory(e.target.value)}><option value="">{t('all')}</option>{[...new Set(rows.filter(r=>r.kind===kind).map(r=>r.territory))].sort((a,b)=>a.localeCompare(b,lang,{numeric:true})).map(r=><option key={r}>{r}</option>)}</select></div><div className="election-count"><span>{visible.length} {t('results')}</span>{selected.length>=2&&<Link href={`/comparar?ids=${selected.join(',')}`}>{t('compare')} ({selected.length}/8) <ArrowUpRight size={15} aria-hidden="true"/></Link>}</div><p className="workspace-scroll-hint">{t('scroll')}</p><div className="election-table" role="region" aria-label={t('title')} tabIndex={0}><table><thead><tr><th>{t('name')}</th><th>{t('territory')}</th><th>{t('party')}</th><th>{t('votes')}</th><th>{t('share')}</th><th>{t('source')}</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><th scope="row"><div className="election-person">{r.profile&&<><input type="checkbox" aria-label={`${t('select')}: ${r.profile.name}`} checked={selected.includes(r.profile.id)} disabled={!selected.includes(r.profile.id)&&selected.length>=8} onChange={e=>setSelected(e.target.checked?[...selected,r.profile!.id]:selected.filter(id=>id!==r.profile!.id))}/><Portrait src={r.profile.portrait} name={r.profile.name}/></>}<span>{r.name}{r.profile&&<Link href={`/politician/${r.profile.id}`}>{t('profile')} <ArrowUpRight size={15} aria-hidden="true"/></Link>}</span></div></th><td>{r.territory}<small>{r.province}</small></td><td><div className="election-party"><img src={getPartyLogoPath(electionParty(r.party))} alt={r.party}/><span>{r.party}</span></div></td><td className="election-votes">{r.votes.toLocaleString(lang)}</td><td>{'percent' in r&&typeof r.percent==='number'?`${r.percent.toLocaleString(lang,{maximumFractionDigits:1})}%`:'—'}</td><td><a href={r.source} target="_blank" rel="noreferrer">CSV <ArrowUpRight size={15} aria-hidden="true"/></a></td></tr>)}</tbody></table></div>{!visible.length&&<p>{t('none')}</p>}</div></main>;
}
