import type {Doc} from '../../../convex/_generated/dataModel';
import Link from 'next/link';
import {ActivityFeed} from './ActivityFeed';
import type {CSSProperties,ReactNode} from 'react';
import {ArrowUpRight,Info,Scale,FileText,Landmark} from 'lucide-react';
import type {DirectoryPerson,ProfileRecord} from '@/lib/reference';
import {archiveRange,displayDate,documentLinks,platformIcon,PLATFORM_NAMES} from '@/lib/reference';
import {getPartyLogoPath,normalizePartyCode} from '@/lib/constants';
import {profileTheme} from '@/lib/profile-presentation';
import {ProfileTabs} from './ProfileTabs';
import {ProfileName} from './ProfileName';
import {Portrait} from './Portrait';
import {SourceLink} from './SourceLink';
import {TabLink} from './TabLink';
import {ProvinceMap} from './ProvinceMap';
import './profile-index.css';

type Props={facts:Doc<'politicianFacts'>|null;initialPanel?:string;person:DirectoryPerson;dashboard:ProfileRecord|null;unavailable:boolean;party:{color:string;secondaryColor?:string}|null;panels:{id:string;label:string;content:ReactNode}[];related:ReactNode};
export function IndexProfile({person:p,dashboard:d,unavailable,party,panels,related,initialPanel,facts}:Props){
 const theme=profileTheme(p.party,party);const docs=documentLinks(d);const range=archiveRange(d);const archive=d?.profile;const t=d?.transparency;const source=t?.espacioCivicoUrl;
 const years=Object.entries((d?.analytics?.monthlyStats||[]).reduce<Record<string,number>>((acc,m)=>{const year=m.month.slice(0,4);acc[year]=(acc[year]||0)+m.totalVotes;return acc;},{})).sort(([a],[b])=>a.localeCompare(b));
 const max=Math.max(1,...years.map(([,v])=>v));const code=normalizePartyCode(p.party);
 const css={'--index-party':theme.primary,'--index-party-ink':theme.ink,'--index-secondary':theme.secondary,'--index-secondary-ink':theme.secondaryInk,'--index-accent-ink':theme.accentInk} as CSSProperties;
 const summary=<div className="index-summary">
  <section data-section-id="profile-overview" className="index-overview"><h2>Perfil</h2><div><p className="index-biography">{t?.biography||facts?.biography||'Biografía pendiente de documentar.'}</p><dl className="index-facts"><div><dt>Nacimiento</dt><dd>{(facts?.birthDate?displayDate(facts.birthDate):d?.bio?.structuredData?.fechaNacimiento)||'Sin documentar'}</dd></div><div><dt>Lugar de nacimiento</dt><dd>{facts?.birthPlace||'Sin documentar'}</dd></div><div><dt>Ciudadanía</dt><dd>{facts?.citizenship||'Sin documentar'}</dd></div></dl>{facts?.sources.map(s=><p className="index-source" key={s.field}><SourceLink href={s.url}>{s.field==='birthDate'?'Fuente de nacimiento':s.field==='birthPlace'?'Fuente de lugar de nacimiento':'Fuente biográfica'}</SourceLink></p>)}<p className="index-source"><SourceLink href={source||p.officialGovUrl}>{source?'Espacio Cívico':'Ficha institucional'}</SourceLink></p></div></section>
  <section data-section-id="profile-docs" className="index-docs"><div className="index-heading"><h2>Documentos</h2><span className="index-count">{String(docs.length).padStart(2,'0')}</span></div>{docs.length?docs.map(doc=><a className="index-document" key={doc.label} href={doc.url} target="_blank" rel="noreferrer"><FileText size={20}/><span>{doc.label}</span><ArrowUpRight size={14}/></a>):<p className="index-empty">Sin documentos enlazados.</p>}<p className="index-source">{docs.length?'Espacio Cívico · documentos públicos':'Cobertura del directorio'}</p></section>
  <section data-section-id="profile-social" className="index-social"><div><h2>Redes</h2><span className="index-count">{String(p.accounts.length).padStart(2,'0')}</span></div><div>{p.accounts.length?p.accounts.map(a=><a className="index-social-account" key={a._id} href={a.profileUrl} target="_blank" rel="noreferrer"><img src={platformIcon(a.platform)} alt="" width={34} height={34}/><span><strong>{PLATFORM_NAMES[a.platform]||a.platform}</strong> · @{a.handle.replace(/^@/,'')}<small>{a.verdict==='CONFIRMED'?'Cuenta identificada':'Identidad probable'}</small></span><ArrowUpRight size={16}/></a>):<p className="index-empty">Sin cuentas registradas.</p>}<p className="index-feed"><TabLink tab="redes">Ver noticias y publicaciones <ArrowUpRight size={14}/></TabLink></p></div></section>
  <section data-section-id="profile-finance" className="index-finance"><h2>Finanzas</h2><dl className="index-facts"><div><dt>Salario personal</dt><dd>Sin documentar</dd></div><div><dt>Patrimonio declarado</dt><dd>{t?.extractedPatrimonio?.patrimonioNeto||'Sin documentar'}</dd></div></dl>{t?.extractedPatrimonio?.patrimonioNeto&&<p className="index-source">Extracción automática; consultar documento original.</p>}</section>
  <section className="index-activity"><ActivityFeed politicianId={p._id} compact/></section>
  <section data-section-id="profile-archive" className="index-archive"><div><h2>Archivo <br/>legislativo</h2>{range&&<span className="index-period">{range.label}</span>}</div><div>{archive?<><p className="index-caution"><Info size={20}/>{archive.isSuplente?'Registro de suplencia. ':''}Vínculo y período pendientes de validación.</p><div className="index-statistics"><div><strong>{archive.totalVotes.toLocaleString('es-PA')}</strong><span>votos registrados</span></div><div><strong>{archive.sessionsAttended}</strong><span>fechas con votos</span></div><div className="index-bars"><span>Votos por año</span>{years.map(([year,count])=><div key={year}><span>{year}</span><div className="index-bar-track"><i style={{width:`${count/max*100}%`}}/></div><span>{count}</span></div>)}</div></div><div className="index-latest"><h3>Últimos registros</h3>{d?.recentVotes.slice(0,2).map(v=><Link key={v.questionId} href={`/politician/${p.externalId}/voto/${v.questionId}`}><time>{displayDate(v.sessionDate)}</time><span>{v.votingTitle}</span><strong>{v.vote==='a_favor'?'A favor':v.vote==='en_contra'?'En contra':'Abstención'}</strong><ArrowUpRight size={14}/></Link>)}</div><p className="index-source">Asamblea Nacional · archivo importado. No mide asistencia al mandato actual.</p></>:<p className="index-empty">{unavailable?'El archivo no pudo cargarse. Recarga la página para volver a intentarlo.':p.roleCategory==='Deputy'?'Sin archivo legislativo vinculado.':'No aplica al cargo registrado. No hay archivo legislativo vinculado.'}</p>}</div></section>
 </div>;
 return <article data-section-id={`politician-${p.externalId}`} className="profile-index" style={css}>
  <aside className="index-sidebar"><div className="index-name-field"><ProfileName name={p.name}/></div><div className={`index-portrait-frame${p.externalId==='DEP-018'?' index-portrait-close':''}`}><Portrait src={p.hasHeadshot?p.headshot:undefined} name={p.name} className="index-portrait"/></div><div className="index-sidebar-details"><Link href={`/partidos/${code.toLowerCase()}`}><img src={getPartyLogoPath(code)} alt="" width={48} height={48}/><span>{p.partyFull||code}</span><ArrowUpRight size={15}/></Link><p>{p.province}{p.district?` · ${p.district}`:''}</p><SourceLink href={p.officialGovUrl}>Ficha institucional</SourceLink><p className="index-source">Directorio actualizado {displayDate(p.updatedAt)}. La fecha no certifica la vigencia del cargo.</p><Link href="/">Volver al directorio</Link></div></aside>
  <div className="index-main"><header className="index-metadata"><div><span>Cargo</span><Link className="metadata-value" href="/oficinas">{p.roleCategory==='Deputy'&&<img src="/icons/official/asamblea-nacional.png" alt="Asamblea Nacional" width={32} height={34}/>}<strong>{p.role}</strong></Link></div><div><span>Provincia</span><Link className="metadata-value" href={`/territorios?province=${encodeURIComponent(p.province)}`}><ProvinceMap name={p.province}/><strong>{p.province}</strong></Link></div><div><span>{p.circuit?'Circuito':'Ámbito'}</span><Link className="metadata-value" href={`/territorios?${p.circuit?'circuit':p.district?'district':'province'}=${encodeURIComponent(p.circuit||p.district||p.province)}`}><strong>{p.circuit||p.district||p.province}</strong><ArrowUpRight size={15}/></Link></div><Link className="index-party-label" href={`/partidos?name=${encodeURIComponent(p.partyFull)}`}><img src={getPartyLogoPath(code)} alt="" width={44} height={44}/><span><span>Partido / agrupación</span><strong>{p.partyFull||code}</strong></span></Link><Link className="index-compare" href={`/comparar?a=${p.externalId}`}><Scale size={20}/>Comparar</Link></header>
  <div className="index-content"><ProfileTabs initialActive={initialPanel} panels={[{id:'perfil',label:'Perfil',content:summary},...panels]}/><div className="index-bottom"><span><Landmark size={16}/>{p.roleCategory==='Deputy'?'Asamblea Nacional':'Directorio de personas públicas'}{p.roleCategory==='Deputy'&&<img src="/icons/official/asamblea-nacional.png" alt="Asamblea Nacional" width={26} height={28}/>}</span><Link href="/metodologia">Fuentes y metodología <ArrowUpRight size={14}/></Link></div><div className="reference-world index-related">{related}</div></div></div>
 </article>;
}
