'use client';
import {ArrowUpRight} from 'lucide-react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {useMemo,useState,useSyncExternalStore} from 'react';
import {useQuery} from 'convex/react';
import {api} from '../../../convex/_generated/api';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {platformIcon,PLATFORM_NAMES} from '@/lib/reference';
import {Portrait} from './Portrait';
import './intelligence.css';
const subscribe=(fn:()=>void)=>{window.addEventListener('storage',fn);return()=>window.removeEventListener('storage',fn);};
const language=()=>localStorage.getItem('orwell-panama-language')||'es';
const copy={
 importDate:['Última comprobación de importación','Latest import check','Última verificação de importação'], importCount:['Nuevas publicaciones en esa comprobación','New posts in that check','Novas publicações nessa verificação'], scroll:['Desplázate horizontalmente para ver fechas y cifras','Scroll horizontally to see dates and counts','Role horizontalmente para ver datas e números'], title:['Inteligencia social','Social intelligence','Inteligência social'],intro:['Cómo cambia la comunicación política. Explora las publicaciones guardadas por fecha, plataforma y formato.','How political communication changes. Explore stored posts by date, platform, and format.','Como muda a comunicação política. Explore publicações guardadas por data, plataforma e formato.'],
 archive:['Archivo, no actividad en tiempo real','Archive, not real-time activity','Arquivo, não atividade em tempo real'],note:['Estos datos describen publicaciones importadas. Un mes vacío puede indicar una brecha de recolección. No mide opinión pública, alcance ni intención de voto.','These data describe imported posts. An empty month may indicate a collection gap. This does not measure public opinion, reach, or voting intention.','Estes dados descrevem publicações importadas. Um mês vazio pode indicar uma falha de coleta. Não mede opinião pública, alcance ou intenção de voto.'],
 person:['Persona','Person','Pessoa'],party:['Partido','Party','Partido'],province:['Provincia','Province','Província'],from:['Desde','From','Desde'],to:['Hasta','To','Até'],all:['Todas','All','Todas'],posts:['Publicaciones archivadas','Archived posts','Publicações arquivadas'],people:['Perfiles con publicaciones','Profiles with posts','Perfis com publicações'],latest:['Última publicación archivada','Latest archived post','Última publicação arquivada'],missing:['Sin datos','No data','Sem dados'],trend:['Actividad a lo largo del tiempo','Activity over time','Atividade ao longo do tempo'],chart:['Gráfico','Chart','Gráfico'],table:['Tabla','Table','Tabela'],month:['Mes','Month','Mês'],formats:['Formatos de comunicación','Communication formats','Formatos de comunicação'],short:['Video corto identificado por URL','Short video identified by URL','Vídeo curto identificado pela URL'],video:['Video registrado','Recorded video','Vídeo registrado'],image:['Imagen registrada','Recorded image','Imagem registrada'],unspecified:['Formato no registrado','Format not recorded','Formato não registrado'],formatNote:['El formato se identifica por la URL y los metadatos disponibles. No se infieren tono, ideología o contenido de podcasts.','Formats come from URLs and available metadata. Tone, ideology, and podcast content are not inferred.','Os formatos vêm de URLs e metadados disponíveis. Não se inferem tom, ideologia ou conteúdo de podcasts.'],examples:['Ver la evidencia','See the evidence','Veja as evidências'],open:['Abrir publicación','Open post','Abrir publicação'],health:['Cobertura de las cuentas','Account coverage','Cobertura das contas'],healthNote:['La ausencia de publicaciones en este archivo no demuestra que una cuenta esté inactiva. Consulta el perfil y verifica la recolección antes de cambiar su frecuencia.','No posts in this archive does not prove an account is inactive. Check the profile and verify collection before changing its frequency.','A ausência de publicações neste arquivo não prova que uma conta esteja inativa. Verifique o perfil e a coleta antes de mudar a frequência.'],noPosts:['Sin publicaciones archivadas','No archived posts','Sem publicações arquivadas'],loading:['Cargando archivo…','Loading archive…','Carregando arquivo…'],empty:['No hay publicaciones para estos filtros.','No posts match these filters.','Nenhuma publicação corresponde a estes filtros.'],reset:['Restablecer filtros','Reset filters','Redefinir filtros'],compare:['Comparar perfiles','Compare profiles','Comparar perfis'],period:['Período disponible','Available period','Período disponível'],grouped:['Agrupado por persona y plataforma','Grouped by person and platform','Agrupado por pessoa e plataforma'],count:['publicaciones','posts','publicações'],search:['Buscar por nombre','Search by name','Buscar por nome'],
} as const;
const colors=['#244b42','#ba6d3c','#5d7191','#97536a','#8e833c','#67558a','#3a8192','#707070'];
export function IntelligenceWorkspace(){
 const lang=useSyncExternalStore(subscribe,language,()=> 'es');const li=lang==='en'?1:lang==='pt'?2:0;const t=(key:keyof typeof copy)=>copy[key][li];
 const params=useSearchParams();const initialPerson=params.get('person');
 const data=useQuery(api.intelligence.archive,{});
 const [person,setPerson]=useState('initial'),[party,setParty]=useState(''),[province,setProvince]=useState(''),[platform,setPlatform]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[search,setSearch]=useState(''),[view,setView]=useState<'chart'|'table'>('chart');
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const cohort=useMemo(()=>data?.people.filter(p=>(person==='initial'?(!initialPerson||p.externalId===initialPerson):(!person||p.id===person))&&(!party||p.party===party)&&(!province||p.province===province)&&normalize(p.name).includes(normalize(search)))||[],[data,person,party,province,search,initialPerson]);
 const availableMonths=data?.buckets.map(b=>b.month).sort()||[];
 const endMonth=availableMonths.at(-1);const startDate=endMonth?new Date(`${endMonth}-01T00:00:00Z`):null;if(startDate)startDate.setUTCMonth(startDate.getUTCMonth()-11);const defaultFrom=startDate?startDate.toISOString().slice(0,7):'';const effectiveFrom=from||defaultFrom;
 const ids=new Set(cohort.map(p=>p.id));const buckets=data?.buckets.filter(b=>ids.has(b.person)&&(!platform||b.platform===platform)&&(!effectiveFrom||b.month>=effectiveFrom)&&(!to||b.month<=to))||[];
 const platforms=[...new Set(data?.buckets.map(b=>b.platform)||[])].sort();
 const series=new Map<string,Record<string,string|number>>();
 const months=data?.buckets.map(b=>b.month).sort()||[];const first=effectiveFrom||months[0],last=to||months.at(-1);
 if(first&&last&&first<=last){const cursor=new Date(`${first}-01T00:00:00Z`),end=new Date(`${last}-01T00:00:00Z`);while(cursor<=end){const month=cursor.toISOString().slice(0,7);series.set(month,{month,...Object.fromEntries(platforms.map(p=>[p,0]))});cursor.setUTCMonth(cursor.getUTCMonth()+1);}}
 for(const b of buckets){const point=series.get(b.month);if(point)point[b.platform]=Number(point[b.platform]||0)+b.count;}
 const chart=[...series.values()];const total=buckets.reduce((sum,b)=>sum+b.count,0);const latest=buckets.reduce((max,b)=>Math.max(max,b.latest),0);const formats=['short','video','image','unspecified'] as const;
 const date=(n:number)=>new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeZone:'America/Panama'}).format(n);
 const dateMonth=(m:string)=>new Intl.DateTimeFormat(lang,{month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${m}-01T00:00:00Z`));
 const accounts=data?.accounts.filter(a=>ids.has(a.person)&&(!platform||a.platform===platform))||[];
 return <main className="reference-world intelligence-workspace" data-no-translate><div className="reference-wrap">
  <header className="intelligence-heading"><div><h1>{t('title')}</h1><p>{t('intro')}</p></div><Link href="/comparar">{t('compare')} <ArrowUpRight size={15} aria-hidden="true"/></Link></header>
  <aside className="intelligence-coverage"><strong>{t('archive')}</strong><p>{t('note')}</p>{months.length>0&&<span>{t('period')}: {dateMonth(months[0])} — {dateMonth(months.at(-1)!)}</span>}</aside>
  {!data?<p role="status">{t('loading')}</p>:<>
  <section className="intelligence-filters" aria-label={t('reset')}>
   <label>{t('search')}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('search')}/></label>
   <label>{t('person')}<select value={person==='initial'?(data?.people.find(p=>p.externalId===initialPerson)?.id||''):person} onChange={e=>setPerson(e.target.value)}><option value="">{t('all')}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label>{t('party')}<select value={party} onChange={e=>setParty(e.target.value)}><option value="">{t('all')}</option>{[...new Set(data.people.map(p=>p.party))].sort().map(p=><option key={p}>{p}</option>)}</select></label>
   <label>{t('province')}<select value={province} onChange={e=>setProvince(e.target.value)}><option value="">{t('all')}</option>{[...new Set(data.people.map(p=>p.province))].sort().map(p=><option key={p}>{p}</option>)}</select></label>
   <label>{t('from')}<input type="month" min={months[0]} max={to||months.at(-1)} value={effectiveFrom} onChange={e=>setFrom(e.target.value)}/></label><label>{t('to')}<input type="month" min={effectiveFrom||months[0]} max={months.at(-1)} value={to} onChange={e=>setTo(e.target.value)}/></label>
   <button onClick={()=>{setPerson('');setParty('');setProvince('');setPlatform('');setFrom('');setTo('');setSearch('');}}>{t('reset')}</button>
  </section>
  <nav className="intelligence-platforms" aria-label="Platforms"><button aria-pressed={!platform} onClick={()=>setPlatform('')}>{t('all')}</button>{platforms.map(p=><button key={p} title={PLATFORM_NAMES[p]||p} aria-label={PLATFORM_NAMES[p]||p} aria-pressed={platform===p} onClick={()=>setPlatform(platform===p?'':p)}><img src={platformIcon(p)} alt={PLATFORM_NAMES[p]||p}/></button>)}</nav>
  <div className="intelligence-metrics"><div><span>{t('posts')}</span><strong>{total.toLocaleString(lang)}</strong></div><div><span>{t('people')}</span><strong>{new Set(buckets.map(b=>b.person)).size}</strong></div><div><span>{t('latest')}</span><strong className="intelligence-date">{latest?date(latest):t('missing')}</strong></div></div>
  <section className="intelligence-trend"><header><h2>{t('trend')}</h2><div><button aria-pressed={view==='chart'} onClick={()=>setView('chart')}>{t('chart')}</button><button aria-pressed={view==='table'} onClick={()=>setView('table')}>{t('table')}</button></div></header>
  {!total?<p>{t('empty')}</p>:view==='chart'?<><div className="intelligence-chart" role="img" aria-label={`${t('posts')}: ${total}. ${t('table')}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month" tickFormatter={dateMonth} minTickGap={40}/><YAxis allowDecimals={false}/><Tooltip labelFormatter={value=>dateMonth(String(value))}/>{platforms.filter(p=>!platform||platform===p).map((p,i)=><Area key={p} type="linear" dataKey={p} name={PLATFORM_NAMES[p]||p} stroke={colors[i%colors.length]} fill={colors[i%colors.length]} fillOpacity={.09} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer></div><div className="intelligence-legend">{platforms.filter(p=>!platform||platform===p).map((p,i)=><span key={p}><i style={{background:colors[i%colors.length]}}/><img src={platformIcon(p)} alt={PLATFORM_NAMES[p]||p}/></span>)}</div></>:<div className="intelligence-table-scroll" role="region" aria-label={t('trend')} tabIndex={0}><table><thead><tr><th>{t('month')}</th>{platforms.filter(p=>!platform||platform===p).map(p=><th key={p}><img src={platformIcon(p)} alt={PLATFORM_NAMES[p]||p}/></th>)}</tr></thead><tbody>{chart.map(r=><tr key={String(r.month)}><th scope="row">{dateMonth(String(r.month))}</th>{platforms.filter(p=>!platform||platform===p).map(p=><td key={p}>{r[p]||0}</td>)}</tr>)}</tbody></table></div>}</section>
  <section className="intelligence-formats"><h2>{t('formats')}</h2><p>{t('formatNote')}</p>{formats.map(f=>{const count=buckets.filter(b=>b.format===f).reduce((s,b)=>s+b.count,0);return <div key={f}><span>{t(f)}</span><meter min={0} max={Math.max(total,1)} value={count}/><strong>{count.toLocaleString(lang)}</strong></div>;})}</section>
  <section className="intelligence-examples"><h2>{t('examples')}</h2><div>{data.examples.filter(e=>ids.has(e.person)&&(!platform||e.platform===platform)&&(!effectiveFrom||new Date(e.date).toISOString().slice(0,7)>=effectiveFrom)&&(!to||new Date(e.date).toISOString().slice(0,7)<=to)).slice(0,6).map(e=>{const p=data.people.find(p=>p.id===e.person)!;return <article key={e.url}><Link href={`/politician/${p.externalId}`}><Portrait src={p.portrait} name={p.name}/><strong>{p.name}</strong></Link><img src={platformIcon(e.platform)} alt={PLATFORM_NAMES[e.platform]||e.platform}/><time>{date(e.date)}</time><p>{e.title}</p><a href={e.url} target="_blank" rel="noreferrer">{t('open')} <ArrowUpRight size={15} aria-hidden="true"/></a></article>;})}</div></section>
  <section className="intelligence-health"><h2>{t('health')}</h2><p>{t('importDate')}: {data.lastSocialImport?date(data.lastSocialImport.date):t('missing')} · {t('importCount')}: {data.lastSocialImport?.inserted??t('missing')}</p><p>{t('healthNote')}</p><p className="workspace-scroll-hint">{t('scroll')}</p><div className="intelligence-table-scroll" role="region" aria-label={t('health')} tabIndex={0}><table><thead><tr><th>{t('person')}</th><th aria-label="Platform"/><th>{t('posts')}</th><th>{t('latest')}</th></tr></thead><tbody>{accounts.map(a=>{const p=data.people.find(p=>p.id===a.person)!;const n=a.posts,last=a.latest;return <tr key={a.url}><th scope="row"><Link href={`/politician/${p.externalId}`}>{p.name}</Link><a href={a.url} target="_blank" rel="noreferrer">@{a.handle.replace(/^@/,'')}</a></th><td><img src={platformIcon(a.platform)} alt={PLATFORM_NAMES[a.platform]||a.platform}/></td><td>{n||t('noPosts')}{a.scope==='person-platform'&&<small style={{display:'block'}}>{t('grouped')}</small>}</td><td>{last?date(last):t('missing')}</td></tr>;})}</tbody></table></div></section>
  </>}
 </div></main>;
}
