import Link from 'next/link';
import {ActivityFeed} from './ActivityFeed';
import {TabLink} from '@/components/reference/TabLink';
import {IndexProfile} from '@/components/reference/IndexProfile';
import {notFound} from 'next/navigation';
import {ArrowRight,ArrowUpRight,FileText,Info,Clock} from 'lucide-react';
import {getProfile,getDirectory,getProfileParty} from '@/lib/reference-data';
import {archiveRange,displayDate,documentLinks,PLATFORM_NAMES,platformIcon} from '@/lib/reference';
import {normalizePartyCode} from '@/lib/constants';
import {Portrait} from '@/components/reference/Portrait';
import {SourceLink} from '@/components/reference/SourceLink';
import {VoteArchive} from './VoteArchive';
import {VotingBreakdown} from '@/components/politician-detail/dashboard/VotingBreakdown';
import {VotingTimeline} from '@/components/politician-detail/dashboard/VotingTimeline';
import {PolicyProposalCard} from '@/components/politician-detail/dashboard/PolicyProposalCard';
import {DeclaracionInteresesCard} from '@/components/politician-detail/dashboard/DeclaracionInteresesCard';
import {DeclaracionPatrimonioCard} from '@/components/politician-detail/dashboard/DeclaracionPatrimonioCard';
import {ProfessionalProfile} from '@/components/politician-detail/dashboard/ProfessionalProfile';

type Props={params:Promise<{id:string}>;initialPanel?:string};
function Empty({children}:{children:React.ReactNode}){return <p className="record-empty">{children}</p>}
function Section({title,children,aside}:{title:string;children:React.ReactNode;aside?:React.ReactNode}){return <section className="record-section"><div className="section-heading"><h2>{title}</h2>{aside}</div>{children}</section>}
export default async function ProfilePage({params,initialPanel}:Props){
 const {id}=await params;const data=await getProfile(id);if(!data)notFound();
 const {person:p,dashboard:d,unavailable}=data;const t=d?.transparency;const v=d?.profile;const range=archiveRange(d);const docs=documentLinks(d);const party=normalizePartyCode(p.party);const [people,partyRecord]=await Promise.all([getDirectory(),getProfileParty(party)]);const related=people.filter(x=>x.externalId!==id&&normalizePartyCode(x.party)===party).slice(0,4);
 const biography=t?.biography;const birthday=d?.bio?.structuredData?.fechaNacimiento;
 const source=t?.espacioCivicoUrl;
 const overview=<div className="profile-columns"><div>
  <Section title="La ficha" aside={<SourceLink href={p.officialGovUrl}>Fuente oficial</SourceLink>}>
   <dl className="fact-grid"><div><dt>Cargo registrado</dt><dd>{p.role}</dd></div><div><dt>Partido / agrupación</dt><dd><Link href={`/partidos/${party.toLowerCase()}`}>{p.partyFull || party}</Link></dd></div><div><dt>Provincia</dt><dd><Link href={`/territorios?province=${encodeURIComponent(p.province)}`}>{p.province}</Link></dd></div><div><dt>Circuito</dt><dd>{p.circuit?<Link href={`/territorios?circuit=${encodeURIComponent(p.circuit)}`}>{p.circuit}</Link>:'No consta'}</dd></div><div><dt>Fecha de nacimiento</dt><dd>{birthday || 'No documentada'}</dd></div><div><dt>Lugar de nacimiento</dt><dd className="record-muted">No documentado</dd></div><div><dt>Ciudadanía</dt><dd className="record-muted">No documentada</dd></div><div><dt>Suplente registrado</dt><dd>{t?.suplente || 'No consta'}</dd></div></dl>
   <p className="source-note">Directorio ORWELL · registro actualizado {displayDate(p.updatedAt)}. La fecha del registro no certifica la vigencia del cargo.</p>
  </Section>
  <Section title="Perfil profesional" aside={<SourceLink href={source}>Espacio Cívico</SourceLink>}>{biography?<p className="biography">{biography}</p>:<Empty>La biografía aún no está documentada en este perfil.</Empty>}</Section>
  <Section title="Trayectoria y elecciones"><div className="career-row">{p.roleCategory==='Deputy'?<img className="career-institution" src="/icons/official/asamblea-nacional.png" alt="Asamblea Nacional" width={36} height={38}/>:<span className="career-dot"/>}<div><strong>{p.role}</strong><p><Link href={`/territorios?province=${encodeURIComponent(p.province)}`}>{p.province}</Link>{p.circuit&&<> · <Link className="territory-tag" href={`/territorios?circuit=${encodeURIComponent(p.circuit)}`}>Circuito {p.circuit}</Link></>}</p><SourceLink href={p.officialGovUrl}>Consultar ficha institucional</SourceLink></div><Link className="source-link" href="/">Ver directorio</Link></div>{v&&range&&<div className="career-row"><span className="career-dot historical"/><div><strong>{v.isSuplente?'Registro de suplencia':'Registro legislativo'} · {range.label}</strong><p>{v.fullName} · Circuito {v.circuit}</p><TabLink tab="votaciones">Consultar registro legislativo <ArrowRight size={14}/></TabLink></div></div>}<p className="record-empty">Resultados electorales y cambios de partido: sin una serie verificada en esta ficha.</p></Section>
 </div><aside>
  <Section title="Documentos públicos" aside={<span className="count-badge">{docs.length}</span>}>{docs.length?docs.map(doc=><a className="document-row" key={doc.label} href={doc.url} target="_blank" rel="noreferrer"><FileText size={18}/><span>{doc.label}</span><ArrowUpRight size={16}/></a>):<Empty>No hay documentos adjuntos.</Empty>}<p className="source-note">Archivo enlazado desde Espacio Cívico. La presencia de un documento no implica auditoría.</p></Section>
  <Section title="Comisiones registradas">{t?.commissions?.length?<ul className="commission-list">{t.commissions.map(c=><li key={c}><Link href={`/comisiones?name=${encodeURIComponent(c)}`}>{c}<ArrowUpRight size={15}/></Link></li>)}</ul>:<Empty>Sin comisiones documentadas.</Empty>}<p className="source-note">Importación sin período publicado. <SourceLink href={source}>Ver composición en la fuente</SourceLink></p></Section>
  <div className="coverage-box"><Info size={18}/><div><strong>El contexto importa</strong><p>Los votos del archivo pertenecen a su período de origen. No son una evaluación del cargo registrado hoy.</p><Link href="/metodologia">Cómo leer los datos <ArrowRight size={14}/></Link></div></div>
 </aside></div>;
 const history=<div>
  <div className="archive-notice"><Clock size={20}/><div><h2>Archivo legislativo{range?` · ${range.label}`:''}</h2><p>{v?`${v.fullName}. ${v.isSuplente?'Registro de suplente. ':''}Circuito ${v.circuit}. `:''}Este vínculo importado no acredita el mandato actual. Las sesiones con voto registrado no equivalen a una tasa de asistencia.</p></div></div>
  {v?<><div className="archive-stats"><div><strong>{v.totalVotes.toLocaleString('es-PA')}</strong><span>Votos registrados</span></div><div><strong>{v.sessionsAttended}</strong><span>Fechas con participación</span></div><div><strong>{range?displayDate(range.end):'No consta'}</strong><span>Última fecha del archivo</span></div></div><div className="two-col"><VotingBreakdown profile={v}/>{d?.analytics?.monthlyStats&&<VotingTimeline monthlyStats={d.analytics.monthlyStats} partyCode={v.partyCode}/>}</div>{d?.recentVotes?.length>0&&<Section title="Votaciones del archivo" aside={<SourceLink href="https://www.asamblea.gob.pa/">Asamblea Nacional</SourceLink>}><p className="source-note">Importación histórica. Abre una votación para consultar su pregunta; no se infiere el resultado de una ley a partir de un voto individual.</p><VoteArchive deputyId={v.deputyId} politicianId={id}/></Section>}<details className="record-details"><summary>Notas sobre participación, afinidad y rankings</summary><p>El conjunto importado mezcla titulares y suplentes. La base cuenta {d?.chamberStats.totalDeputies} registros marcados como principales y {d?.chamberStats.totalSessions} fechas con votos en todo el archivo. Ninguna cifra representa el tamaño actual de la Asamblea ni las sesiones en que esta persona debía asistir. Las tasas, rankings y etiquetas de lealtad no se publican como indicadores comparables hasta verificar mandatos y denominadores.</p></details></>:<Empty>{unavailable?'No pudimos cargar el archivo. Vuelve a intentar recargando esta página.':'No hay un archivo de votaciones vinculado a este perfil. Para cargos ejecutivos, este indicador no aplica.'}</Empty>}
 </div>;
 const finances=<div className="profile-columns"><div><Section title="Remuneración y patrimonio"><dl className="finance-list"><div><dt>Salario personal</dt><dd>No documentado</dd></div><div><dt>Planilla de despacho registrada</dt><dd>{t?.planillaTotal || 'No documentada'}</dd></div><div><dt>Patrimonio neto declarado</dt><dd>{t?.extractedPatrimonio?.patrimonioNeto || 'No documentado'}</dd></div><div><dt>Patrimonio neto estimado</dt><dd>No calculado</dd></div></dl><p className="source-note">Planilla: monto importado de Espacio Cívico, sin fecha de corte documentada. Corresponde al despacho, no al salario ni al patrimonio de la persona. <SourceLink href={source}>Consultar monto en la fuente</SourceLink></p></Section>{t?.extractedIntereses&&<><p className="source-note">Resumen extraído automáticamente del documento. Comprueba el original antes de citarlo.</p><DeclaracionInteresesCard data={t.extractedIntereses} partyCode={party} pdfUrl={t.documents?.declaracionInteresesUrl}/></>}{t?.extractedPatrimonio&&<DeclaracionPatrimonioCard data={t.extractedPatrimonio} partyCode={party} pdfUrl={t.documents?.declaracionPatrimonioUrl}/>}</div><aside><Section title="Evidencia disponible">{docs.filter(d=>d.label.includes('Declaración')).map(doc=><a className="document-row" key={doc.label} href={doc.url} target="_blank" rel="noreferrer"><FileText size={18}/>{doc.label}<ArrowUpRight size={16}/></a>)}<Empty>La falta de un documento aquí no demuestra que la persona no lo haya presentado.</Empty></Section></aside></div>;
 const social=<><Section title="Redes sociales" aside={<span className="record-muted">{p.accounts.length} cuentas registradas</span>}><p className="biography">Accede a las cuentas identificadas en el directorio. Consulta sus publicaciones recogidas y las noticias vinculadas en el feed.</p><div className="social-table">{p.accounts.map(a=><a className="social-row" href={a.profileUrl} key={a.platform} target="_blank" rel="noreferrer"><img src={platformIcon(a.platform)} alt=""/><div><strong>{PLATFORM_NAMES[a.platform]||a.platform}</strong><span>@{a.handle.replace(/^@/,'')}</span></div><span className="record-muted">{a.verdict==='CONFIRMED'?'Identificada en directorio':'Identidad probable'}</span><span className="record-muted">Consultar publicaciones</span><ArrowUpRight size={17}/></a>)}</div></Section><ActivityFeed politicianId={p._id}/></>;
 const sources=<Section title="Fuentes y cobertura"><p className="biography">Cada bloque distingue el registro del directorio, el archivo legislativo y los documentos de terceros. No se presenta una calificación global de la persona.</p><div className="source-register"><div><strong>Ficha institucional</strong><SourceLink href={p.officialGovUrl}>Sitio oficial</SourceLink><p>Cargo y circunscripción. Registro del directorio: {displayDate(p.updatedAt)}.</p></div><div><strong>Espacio Cívico</strong><SourceLink href={source}>Perfil y documentos</SourceLink><p>Biografía, comisiones y declaraciones. La importación no conserva una fecha de corte pública; los valores pueden haber cambiado.</p></div><div><strong>Archivo de la Asamblea Nacional</strong><SourceLink href="https://www.asamblea.gob.pa/">Institución de origen</SourceLink><p>{range?`${displayDate(range.start)} a ${displayDate(range.end)}.`:'Sin fechas disponibles.'} No hay enlace individual a acta en la importación.</p></div><div><strong>Redes sociales</strong><span>{p.accounts.length} cuentas</span><p>Cuentas identificadas y publicaciones recogidas de ORWELL Monitor. Las fechas corresponden al contenido original.</p></div></div><Link className="record-button" href="/metodologia">Leer metodología <ArrowRight size={16}/></Link></Section>;
 const proposals=<><Section title="Propuestas y formación"><p className="source-note">Extracción automática de documentos importados. Las propuestas son compromisos publicados, no resultados verificados.</p>{t?.extractedPropuesta?<PolicyProposalCard data={t.extractedPropuesta} partyCode={party} pdfUrl={t.documents?.propuestaPoliticaUrl}/>:<Empty>No hay propuestas documentadas en esta ficha.</Empty>}</Section>{d?.bio&&<ProfessionalProfile bio={d.bio}/>}</>;
 const relatedContent=related.length>0?<Section title={`Más perfiles · ${p.partyFull||party}`} aside={<Link className="source-link" href={`/?party=${party}`}>Ver todos <ArrowRight size={14}/></Link>}><div className="related-grid">{related.map(r=><Link className="related-person" key={r.externalId} href={`/politician/${r.externalId}`}><Portrait src={r.hasHeadshot?r.headshot:undefined} name={r.name}/><div><strong>{r.name}</strong><span>{r.role} · {r.province}</span></div><ArrowUpRight size={16}/></Link>)}</div></Section>:null;
 return <IndexProfile initialPanel={initialPanel} person={p} dashboard={d} unavailable={unavailable} party={partyRecord} panels={[{id:'trayectoria',label:'Trayectoria',content:overview},{id:'votaciones',label:'Votaciones',content:history},{id:'propuestas',label:'Propuestas',content:proposals},{id:'finanzas',label:'Finanzas',content:finances},{id:'redes',label:'Redes',content:social},{id:'fuentes',label:'Fuentes',content:sources}]} related={relatedContent}/>;
}
